<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper plots">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

	<h2 class="blue">Plots</h2>
	<div id="plotsList" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('plots/_list.phtml', array('plots' => $user->getNonWatching(), 'details' => true)); ?>
	</div>
</div>