<?= $this->doctype(); ?>
<!--[if IE 7]><html class="lt-ie9 lt-ie8" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 8]><html class="lt-ie9" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><!--<![endif]-->
<head>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<meta http-equiv="Content-Language" content="en-US" >
	<title>Every Last Morsel</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300' rel='stylesheet' type='text/css'>
	<link href="/file-bin/css/960/960.css" media="screen" rel="stylesheet" type="text/css">
	<link href="/file-bin/css/welcome.css" media="screen" rel="stylesheet" type="text/css">
	<link rel="shortcut icon" href="/favicon.ico">

	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<script src="/file-bin/js/lib/jquery-1.7.1.min.js" type="text/javascript"></script>
	<script src="/file-bin/js/welcome/main.js" type="text/javascript"></script>
	<script>
	window.fbAsyncInit = function() {
		FB.init({
			appId      : 'YOUR_APP_ID', // App ID
			//channelUrl : '//<?php echo $this->Data()->getDomain() . $this->baseUrl('channel.html'); ?>', // Channel File
			status     : true, // check login status
			cookie     : true, // enable cookies to allow the server to access the session
			xfbml      : true  // parse XFBML
		});
	};

	// Load Asynchronously
	(function(d){
		// FB
		var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
		js = d.createElement('script'); js.id = id; js.async = true;
		js.src = "//connect.facebook.net/en_US/all.js";
		d.getElementsByTagName('head')[0].appendChild(js);

		// g+
		var po = d.createElement('script');
		po.type = 'text/javascript';
		po.async = true;
		po.src = 'https://apis.google.com/js/plusone.js';
		var s = d.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(po, s);
	}(document));
	</script>
</head>

<body id="page">
	<?= $this->layout()->content; ?>
</body>
</html>