<footer id="footer" role="" class="grid_12 clearfix">
	<ul class="list left">
		<li><a href="<?= $this->url('about-us'); ?>">About Us</a></li>
		<li><a href="<?= $this->url(''); ?>">Map A Garden</a></li>
		<li><a href="<?= $this->url('help-us-grow'); ?>">Help Us Grow</a></li>
		<li></li>
	</ul>

	<div class="signups">
		<h4>Help us grow</h4>
		<ul>
			<li></li>
			<li></li>
		</ul>
		<form class="email-signup">
			<input type="email" name="email" />
			<button type="submit" name="submit" class="link-btn">submit</button>
		</form>
		<form class="search">
			<input type="text" name="search" />
			<button type="submit" name="submit" class="link-btn">search</button>
		</form>
	</div>
	<p><a href="http://twitter.com/@everylastmorsel" target="_blank">@everylastmorsel</a></p>
</footer>

<script src="/file-bin/js/lib/bootstrap/bootstrap-button.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-alert.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-modal.js" type="text/javascript"></script>