<footer id="footer" role="" class="grid_12 clearfix">
	<ul class="list grid_3">
		<li><a href="<?= $this->url('/'); ?>">Home</a></li>
		<li><a href="<?= $this->url('faq', array('_route' => 'faq')); ?>">FAQ</a></li>
		<li><a href="<?= $this->url('help', array('_route' => 'help')); ?>">Help</a></li>
	</ul>

	<ul class="list grid_3">
		<li><a href="<?= $this->url('index'); ?>">Home</a></li>
		<li><a href="<?= $this->url('faq', array('_route' => 'faq')); ?>">FAQ</a></li>
		<li><a href="<?= $this->url('help', array('_route' => 'help')); ?>">Help</a></li>
	</ul>
	<p><a href="http://twitter.com/@everylastmorsel" target="_blank">@everylastmorsel</a></p>
</footer>

<script src="/file-bin/js/lib/bootstrap/bootstrap-button.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-alert.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
<script src="/file-bin/js/lib/bootstrap/bootstrap-modal.js" type="text/javascript"></script>