<?php
$_session = Elm::getSingleton('user/session');
?>
<header id="header" role="banner" class="clearfix grid_12">
	<h1>
		<a href="<?= $this->url('/'); ?>" title="Every Last Morsel" class="ext-hide">
			<img src="<?= Elm::getBaseUrl('file-bin/images/logo.png'); ?>" width="100px" alt="Every Last Morsel" title="Every Last Morsel" />
		</a>
	</h1>

	<ul class="list-inline secondary">
		<!--<li id="proximity"><?= $this->User()->getProximity(); ?></li>-->
		<?php if ($_session->isLoggedIn()) : ?>
			<li><a href="<?= $this->url('profile'); ?>">My Account</a></li>
			<li><a href="<?= $this->url(null, array('alias' => $_session->getUser()->getAlias(), '_route' => 'user')); ?>">My Account</a></li>
			<!--<li><a href="<?/*= $this->url('user/messages'); */?>">Messages <?/*= $this->User()->getUnreadMessageCount(true); */?></a></li>-->
			<li><a href="<?= $this->url('profile/settings'); ?>">Settings</a></li>
			<li><a href="<?= $this->url('profile/logout'); ?>">Logout</a></li>
		<?php else : ?>
			<li><a href="<?= $this->url('profile/create'); ?>">Create Account</a></li>
			<li><a href="<?= $this->url('profile/login'); ?>">Login</a></li>
		<?php endif; ?>
	</ul>

	<?php if ($_session->isLoggedIn()) : ?>
	<nav>
		<ul class="list-inline">
			<li><a href="<?= $this->url(''); ?>">Home</a></li>
			<li><a href="<?= $this->url('plots'); ?>" title="Plots">Plots</a></li>
		<?php if ($_session->getUser()->hasPlots()) : ?>
			<li><a href="<?= $this->url('crops'); ?>" title="Crops">Crops</a></li>
		<?php endif; ?>
			<li><a href="<?= $this->url('community'); ?>" title="Community">Community</a></li>
		</ul>
	</nav>
	<?php endif; ?>
</header>