
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<?= $this->headMeta(); ?>
<?= $this->headTitle(); ?>
<?= $this->headStyle(); ?>
<?= $this->headLink(); ?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript"></script>

<?= $this->headScript(); ?>

<script>
window.fbAsyncInit = function() {
	FB.init({
		appId      : 'YOUR_APP_ID', // App ID
		//channelUrl : '//<?php echo $this->Data()->getDomain() . $this->baseUrl('channel.html'); ?>', // Channel File
		status     : true, // check login status
		cookie     : true, // enable cookies to allow the server to access the session
		xfbml      : true  // parse XFBML
	});
};

// Load the SDK Asynchronously
(function(d){
	var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
	js = d.createElement('script'); js.id = id; js.async = true;
	js.src = "//connect.facebook.net/en_US/all.js";
	d.getElementsByTagName('head')[0].appendChild(js);
}(document));
</script>