<!-- application/layouts/scripts/layout.phtml -->
<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?= $this->headMeta(); ?>
	<?= $this->headTitle(); ?>
	<?= $this->headStyle(); ?>
	<?= $this->headLink(); ?>
	<!--
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" type="text/javascript"></script>
     -->
	<?= $this->headScript(); ?>
</head>
<body>
	<div id="page" class="container_12 clearfix">
		<?= $this->render('header.phtml'); ?>
		<?php //= $this->render('modetabs.phtml'); ?>

		<div id="content" role="contentinfo" class="grid_10 clearfix">
			<?= $this->layout()->content; ?>
		</div>

		<?= $this->render('footer.phtml'); ?>
	</div>
</body>
</html>

