<!-- application/layouts/scripts/layout.phtml -->
<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	<?= $this->headMeta(); ?>
	<?= $this->headTitle(); ?>
	<?= $this->headStyle(); ?>
	<?= $this->headLink(); ?>
	<?= $this->headScript(); ?>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript"></script>
	<script type="text/javascript" src="/file-bin/js/helper.js"></script>
	<script type="text/javascript" src="/file-bin/js/elm.js"></script>
	<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=true"></script>
</head>
<body>
	<div id="page" class="container_12 clearfix">
		<?= $this->render('header.phtml'); ?>
		<div id="content" role="contentinfo" class="grid_12 clearfix">
			<?= $this->layout()->content; ?>
		</div>
		<?= $this->render('footer.phtml'); ?>
	</div>

	<div class="overlay" id="overlayMap" style="display: none;">
		<a class="close" onclick="CloseOverlay(this);"></a>
		<div class="content"></div>
	</div>
	<div id="overlayBg" style="display: none;"></div>
</body>
</html>

