<!-- application/layouts/scripts/layout.phtml -->
<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?= $this->render('head.phtml'); ?>
</head>
<body>
	<div id="page" class="container_12 clearfix">
		<?= $this->render('header.phtml'); ?>
		<div id="content" role="contentinfo" class="grid_12 clearfix">
			<?= $this->layout()->content; ?>
		</div>
		<?= $this->render('footer.phtml'); ?>
	</div>
	<div id="fb-root"></div>
</body>
</html>

