<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?= $this->render('head.phtml'); ?>
</head>
<body class="<?= $this->bodyClass; ?> two-column">
	<div class="wrapper">
		<div id="page" class="clearfix">
			<div class="header-container">
				<?= $this->render('header.phtml'); ?>
			</div>

			<div class="main-container">
				<div class="two-column profile-layout clearfix container_12">
					<div class="upper-background"></div>
					<div id="columnLeft" role="aside" class="column-left">
						<?php if (strlen($this->placeholder('sidebar')) > 0) : ?>
							<?= $this->placeholder('sidebar'); ?>
						<?php endif; ?>
					</div>
					<div id="content" role="contentinfo" class="main-content clearfix">
						<?= $this->layout()->content; ?>
					</div>
				</div>
			</div>

			<?= $this->render('footer.phtml'); ?>
		</div>
		<div id="fb-root"></div>
	</div>
</body>
</html>

