<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?= $this->render('head.phtml'); ?>
</head>
<body class="<?= $this->bodyClass; ?>">
	<div class="wrapper">
		<div id="page" class="clearfix">
			<div class="container_12">
				<?= $this->render('header.phtml'); ?>
			</div>

			<div class="two-column clearfix container_12">
				<div id="columnLeft" role="aside" class="grid_3">
					<?php if (strlen($this->placeholder('sidebar')) > 0) : ?>
						<?= $this->placeholder('sidebar'); ?>
					<?php endif; ?>
				</div>
				<div id="content" role="contentinfo" class="grid_9 omega clearfix">
					<?= $this->layout()->content; ?>
				</div>
			</div>

			<?= $this->render('footer.phtml'); ?>
		</div>
		<div id="fb-root"></div>
	</div>
</body>
</html>

