<?php
$_session = Elm::getSingleton('user/session');
$_plot = $this->plot;
/**
 * @TODO implement helper method to display plot images for missing images
 * @TODO implement the scroller for the images
 */
?>
<?php if ($images = $this->plot->getImages()) : ?>
<ul class="list list-block">
	<?php $ctr = 0; ?>
	<?php foreach ($images as $key => $image) : ?>
		<?php if ($ctr++ > 3) break; ?>
		<li><img src="<?= Elm::getBaseUrl('media/plot') . $image->getThumbnail(); ?>" width="150px" title="<?php echo $image->getCaption(); ?>" alt="<?php echo $image->getCaption(); ?>"></li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if ($_session->isLoggedIn() && $this->plot->isAssociated($_session->user)) : ?>
<div id="imageEditContainer">
	<a class="" href="#" id="expandImagesForm" title="Manage Photos">Manage Photos</a>
	<div class="hide">
		<form action="<?php echo $this->url('plot/image-upload', array('p' => $this->plot->getId())); ?>" method="post" enctype="multipart/form-data">
			<ul class="fieldset list-block">
				<li>
					<label for="image-1" class="optional">Image</label>
					<div><input type="file" name="image[]" id="image-1"></div>
				</li>
				<li>
					<label for="caption-1" class="optional">Title/Caption</label>
					<div><input type="text" name="caption[]" id="caption-1" value=""></div>
				</li>
			</ul>
			<p class="buttons-set">
				<a href="#" id="addMore" title="Add Images">Add Another</a>
				<button type="submit" class="btn btn-primary">Upload</button>
			</p>
		</form>
	</div>
</div>

<script defer="defer">
!function($) {
	var total = 1;
	var $imageEditContainer = $('#imageEditContainer');
	$imageEditContainer.on('click', '#expandImagesForm', function(e) {
		e.preventDefault();
		$(this).next().slideToggle();
		$(this).parent().toggleClass('active');
	});

	$imageEditContainer.on('click', '#addMore', function(e) {
		e.preventDefault();
		total++;
		var $ulListInput = jQuery(this).parent().prev();
		var $duplicate = $ulListInput.clone();
		$duplicate.find('input').each(function() {
			var idPrefix = jQuery(this).attr('name').replace('[]', '-');
			$(this).val('').attr('id', idPrefix + total);
			$(this).parent().prev().attr('for', idPrefix + total);
		});
		$ulListInput.after($duplicate);
		return false;
	});
}(window.jQuery);
</script>
<?php endif; ?>