<?php
/**
 * needs:
 * 	user_from_id (current user id)
 * 	user_to_id (user to send to id)
 */
?>
<?php if (Elm::getSingleton('user/session')->isLoggedIn()) : ?>
	<div class="modal hide fade" id="contactModal">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">×</a>
			<h3>Note from...</h3>
		</div>
		<div class="modal-body">
			<?php $form = new Elm_Model_Form_Communication_Contact(); ?>
			<form action="<?php echo $form->getAction() ?>" method="post" id="contactModalForm">
				<input type="hidden" name="from_user_id" value="<?php echo Elm::getSingleton('user/session')->user->getId(); ?>" />
				<?php if (Zend_Registry::isRegistered('current_user')) : ?>
					<input type="hidden" name="to_user_id" value="<?php echo Zend_Registry::get('current_user')->getId(); ?>" />
				<?php else : ?>
					<input type="hidden" name="to_user_id" value="" />
				<?php endif; ?>
				<ul class="fieldset">
					<?php foreach($form->getElements() as $element) : ?>
						<?php echo $element->render(); ?>
					<?php endforeach; ?>
				</ul>
				<div class="buttons-set">
					<a href="#cancel" class="cancel" data-dismiss="modal">cancel</a>
					<button type="submit" class="btn btn-blue" id="contact-submit"><span>Send Note</span></button>
				</div>
			</form>
		</div>
	</div>
	<div class="modal hide fade" id="contactSuccessModal">
		<div class="modal-header"><a class="close" data-dismiss="modal">×</a></div>
		<div class="modal-body">
			<h3>Successfully sent note!</h3>
			<div class="buttons-set">
				<a class="button-link close" data-dismiss="modal">Close</a>
			</div>
		</div>
	</div>
<?php endif; ?>