<div class="left-filters">
	<h3>Communication Hub</h3>
	<ul>
		<li><a href="#inbox" rel="<?php echo $this->url('communication/retrieve', array('type' => 'inbox')); ?>">Inbox</a></li>
		<li><a href="#sent" rel="<?php echo $this->url('communication/retrieve', array('type' => 'sent')); ?>">Sent</a></li>
		<li><a href="#archive" rel="<?php echo $this->url('communication/retrieve', array('type' => 'archive')); ?>">Archive</a></li>
	</ul>
</div>
<script type="text/javascript" src="/file-bin/js/communication.js"></script>