<?php
$message = $this->message;
?>

<h3>Message Details</h3>
<div class="message-contents" id="message-<?php echo $message->getId(); ?>">
	<h4><?php echo $this->escape($message->getSubject()); ?></h4>
	<p class="actions">
		<?php if (!$message->getIsRead()) : ?>
			<span class="icon read" title="Mark Read" rel="<?php echo $this->url('communication/delete', array('mid' => $message->getId())); ?>"></span>
		<?php endif; ?>
		<?php if (!$message->getIsArchived()) : ?>
			<span class="icon archive" title="Archive" rel="<?php echo $this->url('communication/archive', array('mid' => $message->getId())); ?>"></span>
		<?php endif; ?>
		<span class="icon delete" title="Delete" rel="<?php echo $this->url('communication/delete', array('mid' => $message->getId())); ?>"></span>
		<span class="icon reply" title="Reply"></span>
	</p>
	<h5><?php echo $message->getFromUser()->getName(); ?> - <span class="date dark-grey"><?php echo $this->Data()->formatDate($message->getCreatedAt()); ?></span></h5>

	<div class="body">
		<?php echo $this->escape(nl2br($message->getMessage())); ?>
	</div>
</div>
<div class="message-form">
	<form action="<?php echo $this->url('communication/reply', array('mid' => $message->getId())); ?>" method="post">
		<textarea class="reply"></textarea>
	</form>
</div>
<script defer="defer">
jQuery('#v-<?php echo $message->getId(); ?>').on('click', '.icon', function(e) {
	e.preventDefault();
	var $icon = jQuery(this),
		$loader = jQuery('#action-loader'),
		urlString = $icon.attr('rel');

	if ($icon.hasClass('delete')) {
		if (!confirm('Are you sure you would like to delete this message?')) {
			return false;
		}
	}

	$loader.show();
	jQuery.ajax({
		url : urlString,
		complete : function() {
			$loader.hide();
		},
		success : function(response) {
			if (response.success) {
				jQuery('#messageModal').modal('show');
				Elm.success(response);
			}
		},
		error : function() { }
	});
});
</script>