<?php
$message = $this->message;
?>
<h3>Message Details</h3>
<?php echo $this->Message()->render(); ?>
<div class="message-contents" id="message-<?php echo $message->getId(); ?>">
	<h4><?php echo $this->escape($message->getSubject()); ?></h4>
	<p class="actions">
		<?php if (!$message->getIsRead() && $message->getFromUser()->getId() != Elm::getSingleton('user/session')->getUserId()) : ?>
			<span class="icon read" title="Mark Read" rel="<?php echo $this->url('communication/mark-read', array('cid' => $message->getId())); ?>"></span>
		<?php endif; ?>
		<?php if (!$message->getIsArchived() && $message->getFromUser()->getId() != Elm::getSingleton('user/session')->getUserId()) : ?>
			<span class="icon archive" title="Archive" rel="<?php echo $this->url('communication/archive', array('cid' => $message->getId())); ?>"></span>
		<?php endif; ?>
		<?php
			/**<span class="icon delete" title="Delete" rel="<?php echo $this->url('communication/delete', array('cid' => $message->getId())); ?>"></span>*/
		?>
		<span class="icon reply" title="Reply"></span>
	</p>
	<h5><?php echo $message->getFromUser()->getName(); ?> - <span class="date dark-grey"><?php echo $this->Data()->formatDate($message->getCreatedAt()); ?></span></h5>

	<div class="body">
		<?php echo $this->escape(nl2br($message->getMessage())); ?>
	</div>
</div>
<div class="message-form" style="display: none;">
	<form action="<?php echo $this->url('communication/reply', array('mid' => $message->getId())); ?>" method="post">
		<input type="hidden" name="to_user_id" value="<?php echo $message->getFromUser()->getId(); ?>" />
		<input type="hidden" name="from_user_id" value="<?php echo $message->getToUser()->getId(); ?>" />
		<input type="hidden" name="parent_id" value="<?php echo $message->getId(); ?>" />
		<input type="hidden" name="subject" value="Re: <?php echo $message->getSubject(); ?>" />
		<textarea class="reply" name="message" id="reply_message"></textarea>
		<p class="buttons-set">
			<button type="submit" name="reply" class="btn-primary"><span>Reply</span></button>
			<button type="button" class="btn-info btn-cancel"><span>Cancel</span></button>
		</p>
	</form>
</div>
<script defer="defer">
jQuery('.icon.reply').on('click', function(e) {
	jQuery('.message-form').show();
	jQuery('#reply_message').focus();
});
jQuery('.message-form').find('.btn-cancel').on('click', function(e) {
	jQuery('.message-form').hide();
	jQuery('#reply_message').val('');
});
</script>