
<?php if (count($this->plots) > 0) : ?>
	<ul class="list-block">
	<?php foreach ($this->plots as $plot) : ?>
		<li class="crops-grid">
			<h2><?= $plot->getName(); ?></h2>
		<?php if ($plot->getCrops()) : ?>
			<ul>
			<?php foreach ($plot->getCrops() as $crop) : ?>
				<li>
					<?php if ($crop->getIsForSale()) : ?>
					<span class="icons"></span>
					<?php endif; ?>
					<h4><?= $crop->getCrop()->getName(); ?></h4>
					<span><?= $crop->getCondition(); ?></span>
					<span><?= $crop->getDatePlanted(); ?></span>
					<span><?= $crop->getQuantity(); ?></span>
					<span><?= $crop->getYield(); ?></span>
					<span><?= $crop->getPickDate(); ?></span>
					<span>
						<a href="#">Add Yield</a>
					<?php if (!$crop->getIsForSale()) : ?>
						<a href="#">Mark For Sale</a>
					<?php endif; ?>
					</span>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php else : ?>
			<p>You have plots but no crops. Get growing!</p>
		<?php endif; ?>
		</li>
	<?php endforeach; ?>
	</ul>
<?php else : ?>
	<p>You have plots but no crops. Get growing!</p>
<?php endif; ?>