<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
$plots = $user->getNonWatching();
?>
<div class="inner-content-wrapper crops">
	<div class="top">
		<h2><?php echo $user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $user->getCity(); ?>,</li>
			<li><?php echo $user->getState(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>

	<?php if (count($plots)) : ?>
		<ul class="list-block list details">
		<?php foreach ($plots as $plot) : ?>
			<li>
				<figure>
					<img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '150', 'width' => '150'))); ?>" title="<?php echo $plot->getName(); ?>" />
				</figure>
				<div class="plot-details details">
					<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $plot->getName(); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
					<p class="role"><b><?php echo $plot->getUserRole(); ?></b></p>
					<p><?php echo $plot->getAbout(); ?></p>
					<p class="buttons-set">
						<a href="<?php echo $this->url('crops/add', array('p' => $plot->getId())); ?>" class="btn btn-grey" title="Add Crop"><span>Add Crop</span></a>
					</p>
				</div>
				<div class="crops-container">
					<div id="crops" class="blocked-content clearfix">
						<?php echo $this->partial('crops/_list.phtml', array('plot' => $plot)); ?>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	<?php endif; ?>
</div>