<?php if ($feed = $this->User()->getFeed($this->user)) : ?>
<div class="comment-list">
	<h4>Comments</h4>
	<ul class="feed list-block">
		<?php foreach ($feed as $item) : ?>
		<li class="<?php echo $item->getType(); ?>">
			<div class="fLeft">
				<img src="<?php echo $this->User()->getImage($item->getUser()); ?>" title="<?php echo $item->getUser()->getName(); ?>" width="75px" />
		 		<h3><?= $item->getUser()->getName(); ?></h3>
				<p><?= $item->getCreatedAt(); ?></p>
			</div>
			<div class="fLeft">
				<p><?= $item->getContent(); ?></p>
			</div>
		</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>