
<div class="map-container">
	<div id="mapCanvas"></div>
	<div class="bottom"></div>
</div>

<section id="howItWorks" class="container_12">
	<a href="#how-it-works" title="How it works!"></a>
	<h4>Here's how it works:</h4>
	<ul class="list-block">
		<li class="claim-it">
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
		<li class="track-it">
			<h3>Track<br /> your progress</h3>
			<p>Keep tabs on your plants and share results with neighbors and friends.</p>
		</li>
		<li class="learn-it">
			<h3>Learn from others</h3>
			<p>Pick-up on tricks of the trade by following city farms and green thumbs.</p>
		</li>
		<li class="share-it">
			<h3>Share your bumper crop</h3>
			<p>Donate, barter, or exchange IOU's - just don't let it go to waste!.</p>
		</li>
		<li class="build-it">
			<h3>Build a community</h3>
			<p>Establish a potential garden and rally your neighbors to help build it!</p>
		</li>
	</ul>
</section>

<div class="modal hide fade" id="mapModal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3></h3>
	</div>
	<div class="modal-body"></div>
</div>

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=<?php //echo Elm::getAppConfig('mapsapi'); ?>&sensor=true"></script>
<script type="text/javascript" src="//google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>
<script type="text/javascript" src="/file-bin/js/map.js"></script>
<script>
var plots = <?php echo $this->Map()->getPlotJson(); ?>;
var markers = new Array();
var infoWindow = new google.maps.InfoWindow({maxWidth : '200px'});
for (var i = 0; i < plots.length; i++) {
	var plot = plots[i];
	var time = Math.floor(Math.random() * i * 200);
	window.setTimeout(plotPoint, (1000) + time, plot);
}

/**
 * Plots a point on the map based on lat and long
 *
 * @param lat
 * @param long
 */
var infoWindowOpen = '<div class="content mapMarker small plot-info"><div>',
	infoWindowClose = '</div></div>';

var options = {
	boxStyle: { },
	closeBoxMargin: "10px 2px 2px 2px; border: 0",
	closeBoxURL: "/file-bin/images/close.png",
	pane: "floatPane",
	enableEventPropagation: false,
	//disableAutoPan: false,
	maxWidth: 370,
	pixelOffset: new google.maps.Size(-65, -220),
	infoBoxClearance: new google.maps.Size(25, 25),
	zIndex: 50
};
var infoWindow = new InfoBox(options);

function plotPoint(plot) {
	var marker = new google.maps.Marker({
		map: map,
		position: new google.maps.LatLng(plot.latitude, plot.longitude),
		icon: '/file-bin/images/marker-blue.png',
		title: plot.name,
		content: plot.infoWindowHtml,
		draggable: false,
		clickable: true,
		animation: google.maps.Animation.DROP
	});

	markers.push(marker);
	google.maps.event.addListener(marker, 'click', function() {
		infoWindow.setContent(infoWindowOpen + marker.content + infoWindowClose);
		infoWindow.open(map, marker);
	});
}
</script>

