<div class="modal-header">
	<a class="close" data-dismiss="modal">×</a>
	<h3>Fantastic! What do you think about this location?</h3>
</div>
<div class="modal-body step-1" id="stepContent">
	<p class="buttons-set">
		<button id="isA" class="btn btn-primary">Is a Garden</button>
		<button id="shouldBeA" class="btn btn-primary">Should be a Garden</button>
	</p>
</div>
<div class="modal-footer">
	<a href="#" class="btn" data-dismiss="modal">Close</a>
</div>

<script>
jQuery('#stepContent').on('click', 'button', function(e) {
	var $this = jQuery(this),
		$content = jQuery('#stepContent');
	var $alert = $content.find('.alert');

	if ($alert.length) {
		$alert.alert('close');
	}

	jQuery.ajax({
		url: '/index/authenticate/',
		data: 'type=' + $this.attr('id'),
		success: function(response) {
			if (typeof response == 'object') {
				if (response.success) {
					window.location = response.location;
				} else {
					$alert = jQuery.createSuccessAlert(response.message).hide();
				}
			} else {
				jQuery('#mapModal').html(response);
			}

			if ($alert.length) {
				$content.prepend($alert);
				$alert.fadeIn();
			}
		},
		error: function() {
			elm.error("Oops! We've encountered some troubles. Try again shortly!", $content, 'prepend');
		},
		exception: function() {
			elm.error("Oops! We've encountered some troubles. Try again shortly!", $content, 'prepend');
		}
	});
});
</script>
