
<?php $form = new Elm_Model_Form_Yield_Add(); ?>
<form action="<?php echo $form->getAction() ?>" method="post" id="add-yield-form">
	<input type="hidden" name="plot_crop_id" id="plot_crop_id" value="" />
	<ul class="fieldset clearfix">
		<li>
			<label for="quantity">Yield</label>
			<div>
				<input type="text" class="input small" name="quantity" id="quantity" value="<?= $form->getElement('quantity')->getValue(); ?>" />
				<select name="quantity_unit">
					<option value="individual">individual quantity</option>
					<option value="bundles">bundles</option>
				</select>
			</div>
		</li>
		<li>
			<label for="date_picked">Date Picked</label>
			<div>
				<input type="text" class="input small" name="date_picked" id="date_picked" value="<?= $form->getElement('date_picked')->getValue(); ?>" />
			</div>
		</li>
		<li class="purchasable inline" style="display: none">
			<label for="purchasable_quantity">Quantity</label>
			<div>
				<input type="text" class="input small" name="purchasable[quantity]" id="purchasable_quantity" />
			</div>
		</li>
		<li class="purchasable inline" style="display: none">
			<label for="purchasable_price">Price/Unit</label>
			<div>
				<input type="text" class="input small" name="purchasable[price]" id="purchasable_price" />
			</div>
		</li>
	</ul>
	<div class="buttons-set">
		<button type="submit" class="btn btn-blue" name="Add Yield" id="add-yield-submit"><span>Add Yield</span></button>
		<p class="f-left mark-for-sale">Additionally, I'd like to <a href="#" title="Mark Purchasable">put some up for sale?</a></p>
	</div>
</form>
<script defer="defer">
jQuery("#date_picked").datepicker();
jQuery('#add-yield-form').on('submit', function(e) {
	e.preventDefault();
	var $form = jQuery(this);

	/**
	 * @TODO validation
	 */
	//if ($form.find('#purchasable_quantity').val() )

	if ($form.find('.alert').length) {
		$form.find('.alert').remove();
	}

	jQuery.ajax({
		url : $form.attr('action'),
		data : $form.serialize(),
		type : 'post',
		dataType : 'json',
		success : function(response) {
			if (response.success) {
				Elm.success(response.message, $form, 'prepend');
				jQuery.formReset($form);
			} else {
				Elm.error(response.message, $form, 'prepend');
			}
		},
		error : function() {
			Elm.error('There was an error with your request.', $form, 'prepend');
		}
	})
});

jQuery('#add-yield-form').find('.buttons-set a').on('click', function(e) {
	e.preventDefault();
	jQuery(this).parents('.buttons-set').find('.mark-for-sale').hide();
	jQuery('#add-yield-form').find('.purchasable').show();
});
</script>