<?php
$plot = $this->plot;
$session = Elm::getSingleton('user/session');
?>
<div class="top">
	<h2>
		<?php echo $this->escape($plot->getName()); ?>
		<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
			<a href="<?= $this->url('', array('_route' => 'plot-edit', 'p' => $plot->getId())); ?>" title="<?= $this->escape($plot->getName()); ?> Edit">Edit</a>
		<?php endif; ?>
	</h2>
	<ul class="list-inline">
		<li><?php echo $this->escape($plot->getCity()); ?>,</li>
		<li><?php echo $this->escape($plot->getState()); ?></li>
		<li><?php echo $this->escape($plot->getZipcode()); ?></li>
	</ul>
</div>