<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<?php echo $this->partial('plot/_top-display.phtml', array('plot' => $plot)); ?>
	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $plot)); ?>

	<?php if (count($plot->getPendingUsers()) && $session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
		<div class="alert alert-info">
			Look at that, you have pending users. Take a <a href="<?php echo $this->url('plot/pending-users', array('p' => $plot->getId())); ?>">look</a>.
		</div>
	<?php endif; ?>

	<h2 class="blue">People</h2>
	<div id="users" class="blocked-content users-list">
		<?php
			echo $this->partial('plot/user/_list.phtml', array(
				'users' => $plot->getNonWatchers(),
				'canContact' => $this->canContact,
				'details' => true
			));
		?>
		<?php echo $this->partial('plot/user/_associate.phtml', array('plot' => $plot)); ?>
	</div>

	<?php if (count($plot->getWatchers())) : ?>
		<h2 class="blue">Watchers</h2>
		<div id="users" class="blocked-content wathers-list">
			<?php echo $this->partial('user/_list.phtml', array('users' => $plot->getWatchers())); ?>
		</div>
	<?php endif; ?>
</div>


