<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<?php echo $this->partial('plot/_top-display.phtml', array('plot' => $plot)); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $plot)); ?>
	<?php echo $this->Message()->render(); ?>

	<h2 class="blue">
		Photos
		<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
			<a class="action" href="#photosForm" title="Add Photos">Add Photos</a>
		<?php endif; ?>
	</h2>
	<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
		<form id="photosForm" action="<?php echo $this->url('plot/photo-upload', array('p' => $plot->getId())); ?>" method="post" enctype="multipart/form-data" class="no-display photo-form">
			<ul class="fieldset list-block">
				<li>
					<label for="image-1" class="optional">Image</label>
					<div><input type="file" name="image[]" id="image-1"></div>
				</li>
				<li>
					<label for="caption-1" class="optional">Title/Caption</label>
					<div><input type="text" name="caption[]" id="caption-1" value=""></div>
				</li>
			</ul>
			<p class="buttons">
				<a href="#" class="action" id="addPhoto" title="Add Images">Add Another</a>
				<button type="submit" class="btn btn-blue"><span>Upload</span></button>
			</p>
		</form>
		<script>
			var total = 1;
			jQuery('#addPhoto').on('click', function(e) {
				e.preventDefault();
				total++;
				var $ulListInput = jQuery(this).parent().prev();
				var $duplicate = $ulListInput.clone();
				$duplicate.find('input').each(function() {
					var idPrefix = jQuery(this).attr('name').replace('[]', '-');
					jQuery(this).val('').attr('id', idPrefix + total);
					jQuery(this).parent().prev().attr('for', idPrefix + total);
				});
				$ulListInput.after($duplicate);
				return false;
			});
		</script>
	<?php endif; ?>

	<?php echo $this->partial('plot/photos/_timeline.phtml', array('plot' => $plot, 'showRemove' => true)); ?>

	<div class="photo-main blocked-content">
	<?php if ($images = $plot->getImages()) : ?>
		<?php $image = array_shift($images); ?>
		<figure id="photo-main">
			<img src="<?= Elm::getBaseUrl('media/plot') . $image->getThumbnail(); ?>" title="<?php echo $this->escape($image->getCaption()); ?>" alt="<?php echo $this->escape($image->getCaption()); ?>">
		</figure>
	<?php endif; ?>
	</div>
</div>
<script src="/file-bin/js/lib/jquery-simpleSlider.js"></script>
<script defer="defer">
/**
 * Photo timeline main image switch
 *
 * @TODO use bibles.com code for this
 */
jQuery('ul.photo-timeline-list > li').eq(0).addClass('active');
jQuery('ul.photo-timeline-list > li').on('click', 'img', function(e) {
	var $this = jQuery(this);
	jQuery('#photo-main').find('img').attr('src', '');

	// reset active
	$this.parent('li').addClass('active').siblings().removeClass('active');
	jQuery('#photo-main').find('img').fadeOut(200, function() {
		//jQuery(this).attr('src', $this.attr('src').replace('thumbnails', 'fullsize'));
		jQuery(this).attr('src', $this.attr('src'));
		jQuery(this).fadeIn(200);
	});
	jQuery('#photo-main').find('img').error(function(){
		jQuery(this).hide().attr('src',  '/media/placeholder.jpg');
		jQuery(this).fadeIn(200);
	});
});

</script>

