<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<?php echo $this->partial('plot/_top-display.phtml', array('plot' => $plot)); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $plot)); ?>
	<?php echo $this->Message()->render(); ?>

	<?php echo $this->partial('plot/photos/_timeline.phtml', array('plot' => $plot, 'showRemove' => false)); ?>

	<?php if ($plot->getAbout()) : ?>
		<h2 class="blue">About <?= $this->escape($plot->getName()); ?></h2>
		<div id="about" class="blocked-content about-me">
			<p><?= str_replace('<br />', '</p><p>', nl2br($this->escape($plot->getAbout()))); ?></p>
		</div>
	<?php endif; ?>
</div>