<?php
$plot = $this->plot;
$session = Elm::getSingleton('user/session');
$hasYields = $this->Yield()->plotHasYields($plot);
$hasActions = ($session->isLoggedIn() && $plot->isOwner($session->getUser())) || $this->Plot()->hasCropsForSale($plot);
$columnCount = ($hasYields && $hasActions) ? 6 : (($hasYields || $hasActions) ? 5 : 4);
?>
<?php if ($plot->getCrops()) : ?>
	<div class="container" id="crop-list-<?php echo $plot->getId(); ?>">
		<table class="data-table crops" width="100%">
			<colgroup>
				<col class="plant-type" />
				<col class="variety" />
				<col class="date" />
				<col class="coverage" />
			<?php if ($hasYields) : ?>
				<col class="total-yield" />
			<?php endif; ?>
			<?php if ($hasActions) : ?>
				<col class="actions" />
			<?php endif; ?>
			</colgroup>
			<thead>
				<tr>
					<th>Plant Type</th>
					<th>Variety</th>
					<th>Date Planted</th>
					<th>Coverage</th>
				<?php if ($hasYields) : ?>
					<th>Yield</th>
				<?php endif; ?>
				<?php if ($hasActions) : ?>
					<th></th>
				<?php endif; ?>
				</tr>
			</thead>
			<tbody>
			<?php $ctr = 0; ?>
			<?php foreach ($plot->getCrops() as $pCrop) : ?>
				<tr class="<?php echo ($ctr++ % 2) ? '' : 'alt'; ?>">
					<td><?= ucwords($pCrop->getCrop()->getType()); ?></td>
					<td><?= $this->escape($pCrop->getCrop()->getVariety()); ?></td>
					<td><?= $this->Data()->formatDate($pCrop->getDatePlanted()); ?></td>
					<td><?= $pCrop->getCoverage(); ?> <?= $pCrop->getCoverageUnits(); ?></td>
				<?php if ($hasYields) : ?>
					<td id="crop-yields-totals-<?php echo $pCrop->getId(); ?>"><?php echo $this->partial('crops/yields/_totals.phtml', array('pCrop' => $pCrop)); ?></td>
				<?php endif; ?>
				<?php if ($hasActions) : ?>
					<td id="crop-yield-actions-<?php echo $pCrop->getId(); ?>">
						<?php echo $this->partial('crops/list/_actions.phtml', array('pCrop' => $pCrop)); ?>
					</td>
				<?php endif; ?>
				</tr>
				<?php if ($session->isLoggedIn() && $plot->isOwner($session->getUser())) : ?>
					<?php if (count($pCrop->getYields())) : ?>
						<tr class="<?php echo ($ctr % 2) ? '' : 'alt'; ?> nested">
							<td colspan="<?php echo $columnCount; ?>" class="yields" id="crop-yields-<?php echo $pCrop->getId(); ?>">
								<?php echo $this->partial('crops/yields/_list.phtml', array('pCrop' => $pCrop)); ?>
							</td>
						</tr>
					<?php else : ?>
						<tr class="<?php echo ($ctr % 2) ? '' : 'alt'; ?> nested">
							<td colspan="<?php echo $columnCount; ?>" class="yields" id="crop-yields-<?php echo $pCrop->getId(); ?>"></td>
						</tr>
					<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			</tbody>
		</table>

		<?php if ($session->isLoggedIn() && $plot->isOwner($session->getUser())) : ?>
			<div class="modal hide fade crops-modal" id="addYieldModal">
				<div class="modal-header">
					<a class="close" data-dismiss="modal">×</a>
					<h3>Add Yield</h3>
				</div>
				<div class="modal-body">
					<?php echo $this->partial('crops/yields/_form.phtml'); ?>
				</div>
			</div>
			<div class="modal hide fade crops-modal" id="sellThese">
				<div class="modal-header">
					<a class="close" data-dismiss="modal">×</a>
					<h3>Sell These</h3>
				</div>
				<div class="modal-body">
					<?php echo $this->partial('crops/yields/_sell-form.phtml'); ?>
				</div>
			</div>
		<?php endif; ?>
	</div>
<?php else : ?>
	<p>You have yet to plant any crops. Get growin'!</p>
<?php endif; ?>