<?php if (count($this->plots) > 0) : ?>
	<ul class="list-block">
	<?php foreach ($this->plots as $plot) : ?>
		<li>
			<img src="<?php echo $this->Map()->getStaticImage($plot, array('size' => array('height' => '100', 'width' => '100'))); ?>" title="<?php echo $plot->getName(); ?>" />
			<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $plot->getName(); ?>"><?php echo $plot->getName(); ?></a></h3>
			<?php echo $plot->getUserRole(); ?>
		</li>
	<?php endforeach; ?>
	</ul>
<?php else : ?>
	<p>Sorry no plots associated. Get growing!</p>
<?php endif; ?>