<?php
$_session = Elm::getSingleton('user/session');
?>
<div class="clearfix container_12 community">

	<?php //echo $this->partial('community/_navigation.phtml', array('plots' => $_user->getPlots())); ?>

	<div class="blocked-content people">
		<h4>Gardeners & Owners</h4>
		<?php echo $this->partial('user/list.phtml', array('users' => $this->users)); ?>
	</div>

	<div class="blocked-content plots">
		<h4>Plots of Land</h4>
		<?php echo $this->partial('plots/list.phtml', array('plots' => $this->plots)); ?>
	</div>
</div>