<?php
$urlHelper = new Elm_View_Helper_Url();
?>
<tr>
	<td style="padding: 15px;">
		<table>
			<tr>
				<td width="125px">
					<ul style="list-style: none; padding: 0; margin: 0;">
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('about-us'); ?>">About Us</a>
						</li>
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('contact-us'); ?>">Contact Us</a>
						</li>
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('faqs'); ?>">FAQ's</a>
						</li>
					</ul>
				</td>
				<td>
					<ul style="list-style: none; padding: 0; margin: 0;">
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="http://www.facebook.com/everylastmorsel" title="Book 'em!">Facebook</a>
						</li>
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="http://everylastmorsel.tumblr.com/" title="Tumble along">Tumblr</a>
						</li>
						<li style="margin-left: 0;">
							<a style="color: #1DA5B1;" href="http://www.twitter.com/@everylastmorsel" title="Tweet @Everylastmorsel">Twitter</a>
						</li>
					</ul>
				</td>
			</tr>
		</table>
	</td>
</tr>