<?php
$urlHelper = new Elm_View_Helper_Url();
?>
<body style="color: #222; text-align: center">
	<table style="background: #F8F6F4; border-bottom: 2px solid #ccc; color: #666; font-family: arial, sans-serif; font-size: 13px; margin: 0 auto; text-align: left;" width="450">
		<?php echo $this->partial('_header.phtml'); ?>
		<tr>
			<td style="padding: 15px;">
				<p style="color: #1DA5B1; font-size: 16px;">Thanks for showing interest!</p>
				<p>
					We'll be sure to send you an invitation when we're ready
					to launch -- until then we'll be toiling away in the toolshed. Be sure you're taking good notes
					in the mean time -- we're excited to learn what you've got growin' on!
				</p>
				<p>
					Thanks, <br />
					Every Last Morsel
				</p>
			</td>
		</tr>
		<?php echo $this->partial('_footer.phtml'); ?>
	</table>
</body>