<?php
$urlHelper = new Elm_View_Helper_Url();
?>
<body style="color: #222; text-align: center">
	<table style="background: #F8F6F4; border-bottom: 2px solid #ccc; color: #666; font-family: arial, sans-serif; font-size: 13px; margin: 0 auto; text-align: left;" width="450">
		<?php echo $this->partial('_header.phtml'); ?>
		<tr>
			<td style="padding: 15px;">
				<p style="color: #1DA5B1; font-size: 16px;"><?php echo $this->fromUser->getName(); ?> has broke the ice!</p>
				<p>Their reason for contacting you is: <i><?php echo $this->reason; ?></i></p>
				<p><?php echo $this->escape($this->message); ?></p>
				<p style="margin-top: 40px;">
					You can contact this user back directly via <i><?php echo $this->fromUser->getEmail(); ?></i> or you can checkout their
					<a style="color: #1DA5B1;" href="<?php echo $this->fromUser->getUrl(); ?>">profile</a> and contact them
					directly through the site.
				</p>
			</td>
		</tr>
		<?php echo $this->partial('_footer.phtml'); ?>
	</table>
</body>
