<?php
$urlHelper = new Elm_View_Helper_Url();
?>
<body style="color: #222; text-align: center">
	<table style="background: #F8F6F4; border-bottom: 2px solid #ccc; color: #666; font-family: arial, sans-serif; font-size: 13px; margin: 0 auto; text-align: left;" width="450">
		<?php echo $this->partial('_header.phtml'); ?>
		<tr>
			<td style="padding: 15px;">
				<p style="color: #1DA5B1; font-size: 16px;">Welcome, <?php echo $this->user->getFirstname(); ?>!</p>
				<p>Your password is: <i><?php echo $this->password; ?></i></p>
                <p>You can now login to your <a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('/'); ?>">account</a> and start growing with others.</p>
				<!--<p>Please confirm you are who you say you are by clicking the following link:
					<a style="color: #1DA5B1;" href="<?php /*echo $urlHelper->url('profile/confirmation', array('uid' => $this->user->getConfirmationKey())); */?>">
						<?php /*echo $urlHelper->url('profile/confirmation', array('uid' => $this->user->getConfirmationKey())); */?>
					</a>
				</p>-->
			</td>
		</tr>
		<?php echo $this->partial('_footer.phtml'); ?>
	</table>
</body>