<body style="background: #efefef;">
<table>
	<tr>
		<td>ELM Logo</td>
	</tr>
	<tr>
		<td>
			<h1>Welcome to Every Last Morsel!</h1>
			<p><?php echo $this->fromName; ?><?php echo $this->fromEmail; ?></p>
			<p><?php echo $this->message; ?></p>
			<p><a href="#">link to user profile</a></p>
		</td>
	</tr>
	<tr>
		<td>
			<ul>
				<li><a href="#">Privacy Policy</a></li>
				<li><a href="#">Contact Us</a></li>
				<li><a href="#">FAQ</a></li>
			</ul>
		</td>
	</tr>
</table>
</body>