<?php
$urlHelper = new Elm_View_Helper_Url()
?>
<body style="background: #efefef;">
<table>
	<tr>
		<td>ELM Logo</td>
	</tr>
	<tr>
		<td>
			<h1>Welcome to Every Last Morsel!</h1>
			<p><?php echo $this->user->getFirstname(); ?><?php echo $this->user->getLastname(); ?></p>
			<p><?php echo $this->password; ?></p>
			<p>Please confirm you are who you say you are by clicking the following link:
				<a href="<?php echo $urlHelper->url('user/confirmation', array('uid' => $this->user->getConfirmationKey())); ?>">
					<?php echo $urlHelper->url('user/confirmation', array('uid' => $this->user->getConfirmationKey())); ?>
				</a>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<ul>
				<li><a href="#">Privacy Policy</a></li>
				<li><a href="#">Contact Us</a></li>
				<li><a href="#">FAQ</a></li>
			</ul>
		</td>
	</tr>
</table>
</body>