<?php
$urlHelper = new Elm_View_Helper_Url();
?>
<body style="color: #222; text-align: center">
	<table style="background: #F8F6F4; border-bottom: 2px solid #ccc; color: #666; font-family: arial, sans-serif; font-size: 13px; margin: 0 auto; text-align: left;" width="450">
		<?php echo $this->partial('_header.phtml'); ?>
		<tr>
			<td style="padding: 15px;">
				<p style="color: #1DA5B1; font-size: 16px;">Your password has been reset!</p>
				<p>
					<?php echo $this->user->getFirstname(); ?>, your temporary password is: <i><?php echo $this->password; ?></i>.
					Please <a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('profile/login'); ?>">login</a> to your
					account to change your password first thing.
				</p>
				<p>
					If you have received this email by mistake, please let us know <a style="color: #1DA5B1;" href="<?php echo $urlHelper->url('profile/login'); ?>">right away</a>.
					We apologize in advance and will get to the bottom of this.
				</p>
				<p>
					Thanks, <br />
					Every Last Morsel
				</p>
			</td>
		</tr>
		<?php echo $this->partial('_footer.phtml'); ?>
	</table>
</body>