<?php
$urlHelper = new Elm_View_Helper_Url()
?>
<body style="background: #efefef;">
<table>
	<tr>
		<td>ELM Logo</td>
	</tr>
	<tr>
		<td>
			<h1>Password Reset</h1>
			<p><?php echo $this->user->getFirstname(); ?>, your temporary password is: <b><?php echo $this->password; ?></b></p>
			<p>Please <a href="<?php echo $urlHelper->url('profile/login'); ?>">login</a> to your account to reset your password.</p>
		</td>
	</tr>
	<tr>
		<td>
			<ul>
				<li><a href="<?php echo $urlHelper->url('about-us'); ?>">About Us</a></li>
				<li><a href="<?php echo $urlHelper->url('help'); ?>">Help</a></li>
				<li><a href="<?php echo $urlHelper->url('privacy-policy'); ?>">Privacy Policy</a></li>
			</ul>
		</td>
	</tr>
</table>
</body>