<div class="cms-page container_12">
	<h1 class="turquiose">A Little Bit About Us.</h1>

	<p>Every Last Morsel began as a landscaping service oddly enough, and
	that landscaping service began with an assumption. Todd expected a
	great many people would love to have their own garden and grow their
	own food, but they simply didn't have the time or the knowledge to do
	it themselves. If there's room enough to grow grass, then why not grow
	food? And if lawn mowing services exist, then why can't farming
	services too?</p>

	<p>It wasn't long before Todd's list of clients grew quite large. Weeding
	here; watering there; squashing bugs and building beds kept him rather
	busy. And to remember which vegetables grew where was about as much
	fun as playing with a spreadsheet, which is not very fun at all.</p>

	<p>Enter Collin - Todd's high school friend and fellow gardener. As luck
	would have it, he's also quite a talented web developer. Todd pitched
	his idea for a web application to Collin. An application that would
	allow him to map garden locations and list the plant varieties growing
	in each. But expectations didn't remain so modest for long. Todd and
	Collin realized that the concept would be much more interesting, if
	they built it as an open network for everyone - green thumbs and
	foodies alike - because the fun in growing food is sharing it after
	all. And if they made it easy for people to share food, then maybe
	people would be inclined grow more of it!</p>

	<p>The rest, as they say, is history, but here's where the story gets
	really interesting, because you get to choose where it goes from here.
	I don't mean to suggest that you're faced with a choice of donating
	money or buying a latte - though we certainly hope you choose the
	former. Your opportunity to be involved is much greater than that;
	because Every Last Morsel has evolved into a community of people
	inspired to transform their communities by Good Eating. And I can't
	think of a more delicious way to do good than that.</p>

	<p>Sincerely yours,<br />
	Todd, Collin & the gang</p>

	<p><i>P.S. I apologize in advance to any English majors who may have been
	offended by my inability to choose between 1st, 2nd & 3rd person.</i></p>

	<p><i>P.P.S Share your thoughts with us on <a href="https://www.facebook.com/everylastmorsel" target="_blank">Facebook</a>
	or <a href="http://twitter.com/#!/everylastmorsel" target="_blank">Twitter</a>; send us photos of your
	backyard or a meal on your dinner plate. We wanna see everything that happens from pitchfork to salad fork.</i></p>
</div>