<div class="modal-header">
	<a class="close" data-dismiss="modal">×</a>
	<h3>Says Who?</h3>
</div>
<div class="modal-body step-2" id="stepContent">
	<div class="wrapper">
		<div id="login">
			<p>Login to keep plotting</p>
			<form action="<?php echo $this->loginForm->getAction() ?>" method="post" id="loginForm">
				<ul class="fieldset">
					<?php foreach($this->loginForm->getElements() as $element) : ?>
						<?php echo $element->render(); ?>
					<?php endforeach; ?>
				</ul>
			</form>
		</div>

		<div id="middle">
			<p>Some descriptive content to show login or create an account information</p>
		</div>

		<div id="create">
			<p>Create an account and help us connect you with others</p>
			<form action="<?php echo $this->createForm->getAction() ?>" method="post" id="createForm">
				<ul class="fieldset">
					<?php foreach($this->createForm->getElements() as $element) : ?>
						<?php echo $element->render(); ?>
					<?php endforeach; ?>
				</ul>
			</form>
		</div>
	</div>
</div>
<div class="modal-footer">
	<div class="buttons-set middle fLeft">
		<button id="loginSlide" class="btn btn-primary">Login to Account</button>
		<button id="createSlide" class="btn btn-primary">Create Account</button>
	</div>

	<div class="buttons-set login hide fLeft">
		<button id="login-submit" class="btn btn-primary form-submit" data-form="#loginForm">Login</button>
		<a class="" href="#back" title="Back">Back &rang;</a>
	</div>

	<div class="buttons-set create hide fLeft">
		<a class="fLeft" href="#back" title="Back">&lang; Back</a>
		<button id="create-submit" class="btn btn-primary form-submit" data-form="#createForm">Submit</button>
	</div>

	<a href="#" class="btn fRight" data-dismiss="modal">Close</a>
</div>

<script>
var isAGarden = "<?php echo Bootstrap::getSingleton('user/session')->isA; ?>";
var $modal = jQuery('#mapModal'),
	$content = $modal.find('.modal-body'),
	$wrapper = $modal.find('.wrapper'),
	$login = $wrapper.find('#login'),
	$middle = $wrapper.find('#middle'),
	$create = $wrapper.find('#create');

/**
 * Login button click - slide left
 */
jQuery('#loginSlide').on('click', function(e) {
	$wrapper.animate({'left' : -15}, 'fast', function() {
		$login.find('form input').eq(0).focus();
		setButtons('.login');
	})
});

/**
 * Create button click - slide right
 */
jQuery('#createSlide').on('click', function(e) {
	var distance = $login.outerWidth(true) + $middle.outerWidth(true);
	$wrapper.animate({'left' : -distance + 15}, 'fast', function() {
		$create.find('form input').eq(0).focus();
		setButtons('.create');
	})
});

/**
 * back button click - slide right to center
 */
$modal.on('click', 'a[href="#back"]', function(e) {
	e.preventDefault();
	var distance = $login.outerWidth(true);
	$wrapper.animate({'left' : -distance}, 'fast', function() {
		setButtons('.middle');
	});
	return false;
});

function setButtons(className) {
	$modal.find('.modal-footer .buttons-set').hide();
	$modal.find('.modal-footer .buttons-set' + className).show();
}

/**
 * Form submissions
 */
$modal.on('click', '.form-submit', function(e) {
	e.preventDefault();
	var $form = jQuery(jQuery(this).attr('data-form')),
		$alert = $form.find('.alert');

	if ($alert.length) {
		$alert.alert('close');
	}

	jQuery.ajax({
		url: $form.attr('action'),
		type: 'post',
		data: $form.serialize(),
		success: function(response) {
			// if error - show above form
			if (response.error) {
				$alert = jQuery.createErrorAlert(response.message).hide();
				$form.prepend($alert);
				$alert.fadeIn();
			} else if (response.success) {
				jQuery.get('/index/garden-details', function(response) {
					$modal.html(response);
				});
			} else {	// else success show next step
				$modal.html(response);
			}
		},
		error: function() {
			elm.error("Oops! We've encountered some troubles. Try again shortly!", $form, 'prepend');
		},
		exception: function() {
			elm.error("Oops! We've encountered some troubles. Try again shortly!", $form, 'prepend');
		}
	});
	return false;
});
</script>