<div id="step-2">
	<div class="wrapper">
		<div id="login">
			<h4>Login to keep plotting</h4>
			<form action="<?php echo $this->loginForm->getAction() ?>" method="post" id="loginFormValidate">
				<div class="form-message no-display"></div>
				<ul class="fieldset">
					<?php foreach($this->loginForm->getElements() as $element) : ?>
						<?php echo $element->render(); ?>
					<?php endforeach; ?>
				</ul>
				<div class="buttons">
					<button type="submit" name="Submit" id="login-submit">Submit</button>
					<a class="fRight" href="#back" title="Back">Back &rang;</a>
				</div>
			</form>
		</div>

		<div id="middle">
			<h4>Says who?</h4>
			<p class="buttons"><button id="loginSlide">Login to Account</button><button id="createSlide">Create Account</button></p>
		</div>

		<div id="create">
			<h4>Create an account and help us connect you with others</h4>
			<form action="<?php echo $this->createForm->getAction() ?>" method="post" id="createFormValidate">
				<div class="form-message no-display"></div>
				<ul class="fieldset">
					<?php foreach($this->createForm->getElements() as $element) : ?>
						<?php echo $element->render(); ?>
					<?php endforeach; ?>
				</ul>
				<div class="buttons">
					<a class="fLight" href="#back" title="Back">&lang; Back</a>
					<button type="submit" name="Submit" id="create-submit">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
var $wrapper = jQuery('#step-2').find('.wrapper');
var $login = $wrapper.find('#login');
var $middle = $wrapper.find('#middle');
var $create = $wrapper.find('#create');
var isAGarden = <?php echo Bootstrap::getSingleton('user/session')->isA; ?>

/**
 * Login button click - slide left
 */
jQuery('#loginSlide').on('click', function(e) {
	$wrapper.animate({'left' : '0px'}, 'fast', function() {
		jQuery('#login-form-validate input').eq(0).focus();
	})
});

/**
 * Create button click - slide right
 */
jQuery('#createSlide').on('click', function(e) {
	var distance = $login.outerWidth(true) + $middle.outerWidth(true);
	$wrapper.animate({'left' : -distance}, 'fast', function() {
		jQuery('#createFormValidate input').eq(0).focus();
	})
});

/**
 * back button click - slide right to center
 */
$wrapper.find('a[href="#back"]').on('click', function(e) {
	e.preventDefault();
	var distance = $login.outerWidth(true);
	$wrapper.animate({'left' : -distance}, 'fast', function() {
		jQuery('#login-form-validate input').eq(0).blur();
	});
	return false;
});

/**
 * Form submissions
 */
jQuery('form', '#step-2').on('submit', function(e) {
	e.preventDefault();
	var $form = jQuery(this);
	var $wrap = $form.parent();
	jQuery.ajax({
		url: jQuery(this).attr('action'),
		type: 'post',
		data: jQuery(this).serialize(),
		success: function(response) {
			// if error - show above form
			if (response.error) {
				$form.find('.form-message').html(response.message).fadeIn();
			} else if (response.success) {
				jQuery.get('/index/garden-details', function(response) {
					jQuery('#overlayMap').find('.content').html(response);
				})
			} else {	// else success show next step
				jQuery('#overlayMap').find('.content').html(response);
			}
		},
		error: function() {
			alert('error in request');
		},
		exception: function() {
			alert('error in request');
		}
	});
	return false;
});
</script>