
<div class="map-container">
	<div id="mapCanvas"></div>
	<div class="bottom"></div>
</div>

<section id="howItWorks" class="container_12">
	<h4>Here's how it works:</h4>
	<ul class="list-block">
		<li class="claim-it">
			<?php //<figure class="claim"></figure> ?>
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
		<li class="track-it">
			<?php //<figure class="claim"></figure> ?>
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
		<li class="learn-it">
			<?php //<figure class="claim"></figure> ?>
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
		<li class="share-it">
			<?php //<figure class="claim"></figure> ?>
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
		<li class="build-it">
			<?php //<figure class="claim"></figure> ?>
			<h3>Claim your space</h3>
			<p>Simply drop a pin to map your garden's location.</p>
		</li>
	</ul>
</section>

<!--<div id="kickstart" class="container_12">
	<div class="grid_4 content">
		<h3 class="green">Help us get off the ground, so you can start digging in!</h3>
		<p class="grey">Take a quick look at the origins and people behind Every Last Morsel! Visit our Kickstarter page to donate</p>
		<a class="btn oversized btn-yellow" href="#kickstarter"><span><span>Donate Now!</span></span></a>
	</div>
	<div class="grid_8 video">
		video
	</div>
</div>-->

<!--
<div class="modal hide fade edit-modal" id="mapModal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3></h3>
	</div>
	<div class="modal-body"></div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>-->

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=<?php //echo Elm::getAppConfig('mapsapi'); ?>&sensor=true"></script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>
<script type="text/javascript" src="/file-bin/js/map.js"></script>
<script>
var plots = <?php echo $this->Map()->getPlotJson(); ?>;
var markers = new Array();
var infoWindow = new google.maps.InfoWindow({maxWidth : '200px'});
for (var i = 0; i < plots.length; i++) {
	var plot = plots[i];
	var time = Math.floor(Math.random() * i * 200);
	window.setTimeout(plotPoint, (1000) + time, plot);
}

/**
 * Plots a point on the map based on lat and long
 *
 * @param lat
 * @param long
 */
function plotPoint(plot) {
	var marker = new google.maps.Marker({
		map: map,
		title: plot.name,
		draggable: false,
		clickable: true,
		animation: google.maps.Animation.DROP,
		position: new google.maps.LatLng(plot.latitude, plot.longitude),
		content: plot.infoWindowHtml
	});
	markers.push(marker);

	google.maps.event.addListener(marker, 'click', function() {
		console.log(marker.content);
		infoWindow.setContent(marker.content);
		infoWindow.open(map, marker);
	});
}
</script>

