
<h3>Map your Produce</h3>
<div role="aside" class="grid_5 alpha omega left-column">
	left content
</div>
<div class="grid_7 alpha omega right-column">
	<div id="mapCanvas"></div>
</div>
<script type="text/javascript" src="/file-bin/js/map.js"></script>
<script>
var plots = <?php echo $this->Map()->getPlotJson(); ?>;
var markers = new Array();
for (var i = 0; i < plots.length; i++) {
	var plot = plots[i];
	var time = Math.floor(Math.random() * i * 200);
	window.setTimeout(plotPoint, (1000) + time, plot.latitude, plot.longitude);
}
/**
 * Plots a point on the map based on lat and long
 * @param plot
 */
function plotPoint(lat, long) {
	markers.push(new google.maps.Marker({
		map: map,
		draggable: false,
		animation: google.maps.Animation.DROP,
		position: new google.maps.LatLng(lat, long)
	}));
}
</script>

