

<h3>Map your Produce</h3>
<?php
/**
<div role="aside" class="grid_12 alpha omega left-column">
	Left greeting!
</div>
<div class="grid_12 alpha omega right-column">
*/
?>
<div id="mapCanvas"></div>

<div class="modal hide fade edit-modal" id="mapModal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3></h3>
	</div>
	<div class="modal-body"></div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
	</div>
</div>

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=<?php echo Bootstrap::getAppConfig('mapsapi'); ?>&sensor=true"></script>
<script type="text/javascript" src="/file-bin/js/map.js"></script>
<script>
var plots = <?php echo $this->Map()->getPlotJson(); ?>;
var markers = new Array();
for (var i = 0; i < plots.length; i++) {
	var plot = plots[i];
	var time = Math.floor(Math.random() * i * 200);
	window.setTimeout(plotPoint, (1000) + time, plot.latitude, plot.longitude);
}
/**
 * Plots a point on the map based on lat and long
 *
 * @param lat
 * @param long
 */
function plotPoint(lat, long) {
	markers.push(new google.maps.Marker({
		map: map,
		draggable: false,
		animation: google.maps.Animation.DROP,
		position: new google.maps.LatLng(lat, long)
	}));
}
</script>

