<?php
$session = Elm::getSingleton('user/session');
?>
<?php if (Zend_Registry::isRegistered('current_user')) : ?>
	<?php $user = Zend_Registry::get('current_user'); ?>
	<div id="mainImage">
		<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $user->getName(); ?>" width="200px" />
	</div>
	<div id="lowerColumn">
		<?php //if ($session->isLoggedIn() && !$session->user->isMe($_user) && strlen($this->placeholder('contact-modal')) > 0) : ?>
		<?php if ($session->isLoggedIn() && !$session->user->isMe($user) && $this->view->canContact) : ?>
			<?php echo $this->partial('communication/_button.phtml', array('user' => $user)); ?>
		<?php endif; ?>

		<?php if ($session->isLoggedIn() && $session->user->isMe($user)) : ?>
		<!--<ul id="userHub">
			<li>something here</li>
			<li>something here 2</li>
			<li>something here 3</li>
		</ul>-->
		<?php endif; ?>
	</div>
<?php endif; ?>