
<div class="account-create">
	<h1>Create an Account</h1>
    <?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php //echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <ul class="fieldset">
			<?php foreach($this->form->getElements() as $element) : ?>
				<?php echo $element->render(); ?>
			<?php endforeach; ?>
		</ul>
		<div class="button-set">
			<input type="submit" name="submit" id="create-submit" value="submit">
		</div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        //var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
</div>
