<?php
$session = Elm::getSingleton('user/session');
?>
<?php if (count($this->users)) : ?>
	<ul class="list-block user-list">
	<?php foreach ($this->users as $user) : ?>
		<li>
			<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $user->getName(); ?>" width="150px" />
			<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $user->getName(); ?>"><?php echo $user->getName(); ?></a></h3>
			<p>
				<?php if ($session->isLoggedIn() && $session->user->isMe($user)) : ?>
					<i>Me!</i>
				<?php endif; ?>
			</p>
		</li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>