
<div class="account-login">
	<h4>Login to your Account</h4>
    <?php echo $this->Message()->render(); ?>
    <form action="<?php //echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <ul class="fieldset">
			<?php foreach($this->form->getElements() as $element) : ?>
				<?php echo $element->render(); ?>
			<?php endforeach; ?>
		</ul>
		<div class="button-set">
			<input type="submit" name="submit" class="btn btn-primary" id="login-submit" value="submit">
		</div>
    </form>
    <script type="text/javascript"></script>
</div>
