
<div class="account-login">
	<h4>Login to your Account</h4>
    <?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php //echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
			<?php foreach($this->form->getElements() as $element) : ?>
				<?php echo $element->render(); ?>
			<?php endforeach; ?>
		</div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        //var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
</div>
