<div class="account-settings">
	<h4>Account Settings</h4>
    <?php echo $this->Message()->render() ?>
    <form action="<?php //echo $this->form->getActionUrl() ?>" method="post" id="settings-form">
        <ul class="fieldset">
			<?php foreach($this->form->getElements() as $element) : ?>
				<?php echo $element->render(); ?>
			<?php endforeach; ?>
		</ul>
		<div class="button-set">
			<button type="submit" name="Save" id="settings-submit">Save</button>
		</div>
    </form>
</div>
