<?php
$_session = Bootstrap::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper user">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li>
				<strong>Location</strong>
				<span class="editable" data-title="Location" data-name="location" data-type="input"><?php echo $_user->getLocation(); ?></span>
			</li>
		</ul>
		<p class="controls">
			<?php if ($_session->isLoggedIn() && $_session->user->isMe($_user)) : ?>
				<a href="#" class="btn" title="Edit Account Information" data-edit="editable" data-target="#editModalUser" id="editUserTrigger">Edit</a>
			<?php endif; ?>
			<?php if ($_session->isLoggedIn() && $_session->user->isMe($_user) && $this->User()->canShowTips()) : ?>
				<a href="#" title="Tool tips!" class="tips">Tool Tips/help is available</a>
			<?php endif; ?>
		</p>
	</div>

	<ul id="tabMenu" class="list-inline">
		<li><a href="#plots" title="Where I'm Growing">Plots</a></li>
		<li><a href="#feed" title="What's new?">Latest</a></li>
		<li><a href="#about" title="Who am I?">About</a></li>
	</ul>

	<section id="plots" class="blocked-content clearfix">
		<?php if ($plots = $_user->getPlots()) : ?>
			<ul class="list-block">
			<?php foreach ($_user->getPlots() as $plot) : ?>
				<li>
					<img src="<?php echo $this->Map()->getStaticImage($plot, array('size' => array('height' => '100', 'width' => '100'))); ?>" title="<?php echo $plot->getName(); ?>" />
					<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $plot->getName(); ?>"><?php echo $plot->getName(); ?></a></h3>
					<?php echo $plot->getUserRole(); ?>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php else : ?>
			<p>Sorry no plots associated. Get growing!</p>
		<?php endif; ?>
	</section>

	<section id="feed" class="blocked-content">
		<?php $feed = $this->User()->getFeed($_user); ?>

		<?php if (count($feed) > 0) : ?>
		<ul>
		<?php foreach ($feed as $item) : ?>
			<li class="<?php echo $item->getType(); ?>">
				<?php echo $item->getContent(); ?>
				<?php echo $item->getCreatedAt(); ?>
			</li>
		<?php endforeach; ?>
		</ul>
		<?php else : ?>
			<div class="alert alert-info fade in">
				<a class="close" data-dismiss="alert">×</a>
				<p>Hey! Lets get involved.</p>
			</div>
		<?php endif; ?>
	</section>

	<section id="about" class="blocked-content">
		<div class="editable" data-title="About myself" data-name="about" data-type="textarea">
			<?= $_user->getAbout() ? $_user->getAbout() : 'Tell us a little about yourself...'; ?>
		</div>
	</section>
</div>

<div class="modal hide fade edit-modal" id="editModalUser">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3></h3>
	</div>
	<div class="modal-body">
		<form action="<?= $this->url('user/save'); ?>" type="post" id="editFormUser">
			<input type="hidden" data-name="identifier" name="user_id" value="<?= $_user->getId(); ?>" />
			<input type="hidden" data-name="update" name="user_update" value="" />
			<div class="wrapper"></div>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Close</a>
		<a href="#" class="btn btn-primary" data-submit="form" data-form="#editFormUser">Save</a>
	</div>
</div>

<script>
jQuery('#editUserTrigger').on('click', function(e) {
	var $imageForm = jQuery('#imageUploadForm');
	if ($imageForm.length) {
		$imageForm.toggleClass('hide');
	}
});
</script>