<?php
$_session = Bootstrap::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper user">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li>
				<strong>Location</strong>
				<span class="editable" data-name="Location" data-value="<?php echo $_user->getLocation(); ?>"><?php echo $_user->getLocation(); ?></span>
			</li>
		</ul>
		<?php if ($_session->isLoggedIn() && $_session->user->isMe()) : ?>
			<a href="#edit" title="Edit Account Information" id="userEdit">Edit</a>
		<?php endif; ?>
	</div>

	<ul id="tabMenu" class="list-inline">
		<li><a href="#plots" title="Where I'm Growing">Plots</a></li>
		<li><a href="#about" title="Who am I?">About</a></li>
	</ul>

	<section id="plots" class="blocked-content clearfix">
		<?php if ($plots = $_user->getPlots()) : ?>
			<ul class="list-block">
			<?php foreach ($_user->getPlots() as $plot) : ?>
				<li>
					<img src="<?php echo $this->Map()->getStaticImage($plot, array('size' => array('height' => '100', 'width' => '100'))); ?>" title="<?php echo $plot->getName(); ?>" />
					<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $plot->getName(); ?>"><?php echo $plot->getName(); ?></a></h3>
					<?php echo $plot->getUserRole(); ?>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php else : ?>
			<p>Sorry no plots associated. Get growing!</p>
		<?php endif; ?>
	</section>
	<section id="about" class="blocked-content">
		<div class="editable" data-name="about" data-value="<?php echo $_user->getAbout(); ?>">
			About me...
		</div>
	</section>
</div>

<script>
jQuery('#edit').on('click', function(e) {
	var $this = jQuery(this);
	var editableEls = jQuery('.editable');

	editableEls.each(function(key, item) {

	})
});

jQuery('.editable').on('click', function(e) {
	var $this = jQuery(this);
});
</script>