<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper profile">
	<div class="top">
		<h2><?php echo $user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $user->getLocation(); ?></li>
			<li><?php echo $user->getLocation(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('user/_navigation.phtml', array('user' => $user)); ?>

<?php if ($user->isPrivate()) : ?>
	<h2 class="private-user">This user is private.</h2>
<?php else : ?>
	<h2 class="blue">About <?= $user->getFirstname(); ?></h2>
	<div id="about" class="blocked-content about-me">
		<p><?= str_replace('<br />', '</p><p>', nl2br($user->getAbout())); ?></p>
	</div>

	<div id="feed" class="blocked-content">
		<?php //echo $this->partial('profile/feed/list.phtml', array('user' => $user)); ?>
	</div>
<?php endif; ?>
</div>