<?php
$session = Bootstrap::getSingleton('user/session');
if (Zend_Registry::isRegistered('current_plot')) : ?>
	<?php $plot = Zend_Registry::get('current_plot'); ?>
	<div id="mainImage">
		<img src="<?php echo $this->Map()->getStaticImage($plot); ?>" title="" />
	</div>
	<div id="lowerColumn">
	<?php if ($session->isLoggedIn() && $plot->isAssociated($session->user)) : ?>
		<ul id="userHub">
			<li>something here</li>
			<li>something here 2</li>
			<li>something here 3</li>
		</ul>
	<?php endif; ?>
	</div>
<?php endif; ?>