<?php
$_session = Elm::getSingleton('user/session');
$_plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<div class="top">
		<h2><?php echo $_plot->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_plot->getCity(); ?>,</li>
			<li><?php echo $_plot->getState(); ?></li>
			<li><?php echo $_plot->getZipcode(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $_plot)); ?>

	<h2 class="blue">Crops</h2>
	<div id="crops" class="blocked-content crops">
		<?php echo $this->partial('crops/list.phtml', array('plots' => array($_plot))); ?>
	</div>

	<?php if (count($_plot->getPendingUsers()) && $_session->isLoggedIn() && $_plot->isOwner($_session->user)) : ?>
		<form action="<?php echo $this->url('plot/image-upload', array('p' => $_plot->getId())); ?>" method="post" enctype="multipart/form-data">
			<ul class="fieldset list-block">
				<li>
					<label for="image-1" class="optional">Image</label>
					<div><input type="file" name="image[]" id="image-1"></div>
				</li>
				<li>
					<label for="caption-1" class="optional">Title/Caption</label>
					<div><input type="text" name="caption[]" id="caption-1" value=""></div>
				</li>
			</ul>
			<p class="buttons">
				<a href="#" id="addMore" title="Add Images">Add Another</a>
				<button type="submit">Upload</button>
			</p>
		</form>
	<?php endif; ?>
</div>


