<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<div class="top">
		<h2><?php echo $plot->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $plot->getCity(); ?>,</li>
			<li><?php echo $plot->getState(); ?></li>
			<li><?php echo $plot->getZipcode(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $plot)); ?>

	<h2 class="blue">Crops
		<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
			<a class="action" href="<?php echo $this->url('crops/add/', array('p' => $plot->getId())); ?>" title="Add Crop">Add Crop</a>
		<?php endif; ?>
	</h2>
	<div id="crops" class="blocked-content crops">
		<?php echo $this->partial('crops/_list.phtml', array('plot' => $plot)); ?>
	</div>
</div>


