<?php
$_session = Bootstrap::getSingleton('user/session');
$_plot = $this->plot;
?>

<?php echo $this->Message()->render(); ?>

<div class="inner-content-wrapper plot">
	<h2>
		<?php echo $_plot->getName(); ?>
		<?php if ($_session->isLoggedIn() && $_plot->isAssociated($_session->user)) : ?>
			<a href="#edit" title="Edit Plot Information" id="plotEdit">Edit</a>
		<?php endif; ?>
	</h2>

	<h3>Current images</h3>
	<section class="photo-timeline">
		<?php if ($images = $_plot->getImages()) : ?>
		<ul class="list list-block">
			<?php foreach ($images as $image) : ?>
				<li><img src="<?= $image->getUrl(); ?>" title="<?php echo $image->getTitle(); ?>" alt="<?php echo $image->getTitle(); ?>"></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		<a href="<?php echo $this->url('plot/images', array('p' => $_plot->getId())); ?>" title="Manage Photos">Manage Photos</a>
	</section>

	<form action="<?php echo $this->url('plot/image-upload', array('p' => $_plot->getId())); ?>" method="post" enctype="multipart/form-data">
		<ul class="input-fields">
			<li>
				<input type="file" name="image[]" title="Upload Image" />
			</li>
			<li>
				<a href="#" id="addMore" title="Add Images">Add Another</a>
			</li>
		</ul>
		<p class="buttons">
			<button type="submit">Upload</button>
		</p>
	</form>
</div>

<script>
//(function($) {
	jQuery('#addMore').on('click', function(e) {
		var $liListInput = jQuery(this).parent().prev();
		var $duplicate = $liListInput.clone();
		$duplicate.find('input').val('');
		$liListInput.after($duplicate);
	});
//})(jQuery);
</script>

