<?php
$_session = Bootstrap::getSingleton('user/session');
$_plot = $this->plot;
?>

<?php echo $this->Message()->render(); ?>

<div class="inner-content-wrapper plot">
	<h2><a href="<?php echo $_plot->getUrl(); ?>" title="<?php echo $_plot->getName(); ?>"><?php echo $_plot->getName(); ?></a></h2>
	<h4>Current images</h4>
	<section class="photo-timeline">
		<?php if ($images = $_plot->getImages()) : ?>
		<ul class="list list-block">
			<?php foreach ($images as $image) : ?>
				<li>
					<img src="<?= Bootstrap::getBaseUrl('media/plot') . $image->getThumbnail(); ?>" width="150px" title="<?php echo $image->getCaption(); ?>" alt="<?php echo $image->getCaption(); ?>">
					<a href="<?= $this->url('plot/image-remove', array('p' => $_plot->getId(), 'images' => $image->getId())); ?>" title="Remove Image">Remove</a>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</section>

	<form action="<?php echo $this->url('plot/image-upload', array('p' => $_plot->getId())); ?>" method="post" enctype="multipart/form-data">
		<ul class="fieldset list-block">
			<li>
				<label for="image-1" class="optional">Image</label>
				<div><input type="file" name="image[]" id="image-1"></div>
			</li>
			<li>
				<label for="caption-1" class="optional">Title/Caption</label>
				<div><input type="text" name="caption[]" id="caption-1" value=""></div>
			</li>
		</ul>
		<p class="buttons">
			<a href="#" id="addMore" title="Add Images">Add Another</a>
			<button type="submit">Upload</button>
		</p>
	</form>
</div>


