<?php
$_session = Elm::getSingleton('user/session');
$_plot = $this->plot;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper profile plot">
	<div class="top">
		<h2><?php echo $_plot->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_plot->getCity(); ?>,</li>
			<li><?php echo $_plot->getState(); ?></li>
			<li><?php echo $_plot->getZipcode(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $_plot)); ?>

	<h2 class="blue">People</h2>
	<div id="users" class="blocked-content users-list">
		<?php if (count($_plot->getPendingUsers()) && $_session->isLoggedIn() && $_plot->isOwner($_session->user)) : ?>
			<div class="alert alert-info">
				You have pending users! Please review and take <a href="<?php echo $this->url('plot/pending-users', array('p' => $_plot->getId())); ?>">action</a>
			</div>
		<?php endif; ?>
		<?php echo $this->partial('plot/users/list.phtml', array('users' => $_plot->getUsers())); ?>

		<?php if ($_session->isLoggedIn() && !$_plot->isAssociated($_session->user)) :  ?>
			<?php echo $this->partial('plot/users/associate.phtml', array('plot' => $_plot)); ?>
		<?php endif; ?>
	</div >
</div>


