<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<div class="top">
		<h2><?php echo $plot->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $plot->getCity(); ?>,</li>
			<li><?php echo $plot->getState(); ?></li>
			<li><?php echo $plot->getZipcode(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $plot)); ?>

	<h2 class="blue">Photos
		<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
			<a class="action" href="#photosForm" title="Add Photos">Add Photos</a>
		<?php endif; ?>
	</h2>
	<?php if ($session->isLoggedIn() && $plot->isOwner($session->user)) : ?>
		<form id="photosForm" action="<?php echo $this->url('plot/photo-upload', array('p' => $plot->getId())); ?>" method="post" enctype="multipart/form-data" class="no-display photo-form">
			<ul class="fieldset list-block">
				<li>
					<label for="image-1" class="optional">Image</label>
					<div><input type="file" name="image[]" id="image-1"></div>
				</li>
				<li>
					<label for="caption-1" class="optional">Title/Caption</label>
					<div><input type="text" name="caption[]" id="caption-1" value=""></div>
				</li>
			</ul>
			<p class="buttons">
				<a href="#" id="addPhoto" title="Add Images">Add Another</a>
				<button type="submit" class="btn btn-blue"><span>Upload</span></button>
			</p>
		</form>
		<script>
			var total = 1;
			jQuery('#addPhoto').on('click', function(e) {
				e.preventDefault();
				total++;
				var $ulListInput = jQuery(this).parent().prev();
				var $duplicate = $ulListInput.clone();
				$duplicate.find('input').each(function() {
					var idPrefix = jQuery(this).attr('name').replace('[]', '-');
					jQuery(this).val('').attr('id', idPrefix + total);
					jQuery(this).parent().prev().attr('for', idPrefix + total);
				});
				$ulListInput.after($duplicate);
				return false;
			});
		</script>
	<?php endif; ?>

	<div class="photo-timeline blocked-content">
		<?php echo $this->partial('plot/photos/timeline.phtml', array('plot' => $plot, 'showRemove' => true)); ?>
	</div>

	<div class="photo-main blocked-content">
	<?php if ($images = $plot->getImages()) : ?>
		<?php $image = array_shift($images); ?>
		<figure>
			<img src="<?= Elm::getBaseUrl('media/plot') . $image->getThumbnail(); ?>" title="<?php echo $image->getCaption(); ?>" alt="<?php echo $image->getCaption(); ?>">
		</figure>
	<?php endif; ?>
	</div>
</div>


