<?php
$_session = Elm::getSingleton('user/session');
$_plot = $this->plot;
?>
<div class="inner-content-wrapper profile plot">
	<div class="top">
		<h2><?php echo $_plot->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_plot->getCity(); ?></li>
			<li><?php echo $_plot->getState(); ?></li>
			<li><?php echo $_plot->getZipcode(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>

	<?php echo $this->partial('plot/_navigation.phtml', array('plot' => $_plot)); ?>

	<div class="photo-timeline blocked-content">
		<?php echo $this->partial('plot/photos/timeline.phtml', array('plot' => $_plot, 'showRemove' => false)); ?>
	</div >

	<?php if ($_plot->getAbout()) : ?>
		<h2 class="blue">About <?= $_plot->getName(); ?></h2>
		<div id="about" class="blocked-content about-me">
			<p><?= str_replace('<br />', '</p><p>', nl2br($_plot->getAbout())); ?></p>
		</div>
	<?php endif; ?>
</div>