<?php
$_session = Bootstrap::getSingleton('user/session');
$_plot = $this->plot;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper plot">
	<div class="top">
		<h2><span class="editable" data-name="name" data-type="input"><?php echo $_plot->getName(); ?></span></h2>
		<ul class="list-inline">
			<li><strong>Location</strong> <?php echo $_plot->getZipcode(); ?></li>
		</ul>
		<?php if ($_session->isLoggedIn() && $_plot->isAssociated($_session->user)) : ?>
			<a href="#edit" title="Edit Plot Information" class="plot-edit">Edit</a>
		<?php endif; ?>
		<?php if ($_session->isLoggedIn() && $_plot->isAssociated($_session->user) && $this->User()->canShowTips()) : ?>
			<a href="#tips" title="Tool tips!" class="tips">Tool Tips</a>
		<?php endif; ?>
	</div>

	<section class="photo-timeline">
		<?php
			// @TODO make a partial or whatever it is called
		?>
		<?php if ($images = $_plot->getImages()) : ?>
		<ul class="list list-block">
			<?php foreach ($images as $image) : ?>
				<li><img src="<?= Bootstrap::getBaseUrl('media/plot') . $image->getThumbnail(); ?>" width="150px" title="<?php echo $image->getCaption(); ?>" alt="<?php echo $image->getCaption(); ?>"></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		<?php if ($_session->isLoggedIn() && $_plot->isAssociated($_session->user)) : ?>
			<a href="<?php echo $this->url('plot/images', array('p' => $_plot->getId())); ?>" title="Manage Photos">Manage Photos</a>
		<?php endif; ?>
	</section>

	<ul id="tabMenu" class="list-inline">
		<li><a href="#plots" title="Where I'm Growing">Users</a></li>
		<li><a href="#socializing" title="What I'm Sharing">Status</a></li>
		<li><a href="#crops" title="What I'm Growing">Crops</a></li>
		<li><a href="#about" title="Who am I?">About</a></li>
	</ul>

	<section id="users" class="blocked-content">
		<?php if ($users = $_plot->getUsers()) : ?>
			<ul>
			<?php foreach ($users as $user) : ?>
				<li>
					<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $user->getName(); ?>"><?php echo $user->getName(); ?></a></h3>
					<?php echo $user->getUserRole(); ?>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php else : ?>
			<p>Sorry no users associated. Get growing!</p>
		<?php endif; ?>
		<?php if ($_session->isLoggedIn() && !$_plot->isAssociated($_session->user)) :  ?>
			<p><button class="button" name="get-involved" id="get-involved">Get Involed</button></p>
		<?php endif; ?>
	</section>

	<section id="socializing" class="blocked-content">
	<?php //if ($_session->isLoggedIn() && $_plot->isAssociated($_session->user)) :  ?>
		<!--<form action="<?php /*echo $this->url(''); */?>" method="post">-->
			<p class="input">
				<label for="blub">How's it growin'?</label>
				<textarea id="blurb" name="blurb"></textarea>
			</p>
			<p class="buttons">
				<button class="button" type="submit">Share</button>
			</p>
		<!--</form>-->
	<?php //endif; ?>
		<h5>Thoughts:</h5>
		<ul class="feed">
			<li>
				<h4>user name</h4>
				<p>What is your git version and where have you got it from? Is your .gitignore written exactly like this
					(case, some hidden extension, like they do on Windows)? Any invisible characters in .gitignore?</p>
			</li>
			<li>
				<h4>user name</h4>
				<p>What is your git version and where have you got it from? Is your .gitignore written exactly like this
					(case, some hidden extension, like they do on Windows)? Any invisible characters in .gitignore?</p>
			</li>
			<li>
				<h4>user name</h4>
				<p>What is your git version and where have you got it from? Is your .gitignore written exactly like this
					(case, some hidden extension, like they do on Windows)? Any invisible characters in .gitignore?</p>
			</li>
		</ul>
	</section>
	<section id="crops" class="blocked-content">
		Crop display
	</section>
	<section id="about" class="blocked-content">
		<div class="editable" data-name="about" data-type="textarea">
			<?= $_plot->getAbout() ? $_plot->getAbout() : 'A little about this plot...'; ?>
		</div>
	</section>
</div>

<div class="overlay" id="plot-edit-overlay" style="display: none;">
	<a class="close" onclick="CloseOverlay(this);"></a>
	<div class="content">
		<form action="<?= $this->url('plot/save'); ?>" type="post" id="plot-save-form">
			<div class="form-message no-display"></div>
			<input type="hidden" name="plot_id" value="<?= $_plot->getId(); ?>" />
			<input type="hidden" name="plot_update" value="" />
			<div class="middle"></div>
			<button type="submit" class="button" name="Update">Update</button>
		</form>
	</div>
</div>
<script>
// This is my personal plot!
jQuery('.plot-edit').on('click', function(e) {
	var $this = jQuery(this);
	var editableEls = jQuery('.editable');
	var $form = jQuery('#plot-save-form');

	if ($this.hasClass('editing')) {
		$this.removeClass('editing');
		$this.html('Edit');
		editableEls.each(function(key, item) {
			var $el = jQuery(item);
			if ($el.next().hasClass('update-button')) {
				$el.next().remove();
			}
		});
	} else {
		$this.addClass('editing');
		$this.html('Done Editing');
		editableEls.each(function(key, item) {
			var $el = jQuery(item);
			if (!$el.next().hasClass('update-button')) {
				$el.after('<button class="update-button button">Update</button>');
			}
		});
	}
});

jQuery(document).on('click', '.update-button', function(e) {
	e.preventDefault();
	var $this = jQuery(this);
	var $form = jQuery('#plot-save-form');
	var $el = $this.prev();

	if ($el.attr('data-type') == 'textarea') {
		var $input = jQuery('<textarea name="' + $el.attr('data-name') + '" id="">' +  $el.html().trim() + '</textarea>');
	} else {
		var $input = jQuery('<input type="' + $el.attr('data-type') + '" name="' + $el.attr('data-name') + '" id="" value="' +  $el.html().trim() + '" />');
	}

	$form.find('.middle').html($input);
	$form.find('input[name="plot_update"]').val($el.attr('data-name'));
	jQuery('#plot-edit-overlay').fadeIn();
	jQuery('#overlayBg').fadeIn();
});

jQuery('#plot-save-form').on('submit', function(e) {
	e.preventDefault();
	var $form = jQuery(this);

	jQuery.ajax({
		url: '/plot/save/',
		type: 'post',
		data: $form.serialize(),
		success: function(response) {
			if (typeof response == 'object') {
				jQuery('.form-message', $form).html(response.message).fadeIn();

				var editedValue = $form.find('input[name="plot_update"]').val();
				jQuery('.editable').each(function(key, item) {
					var $el = jQuery(item);
					if ($el.attr('data-name') == editedValue) {
						$el.html(response.value);
					}
				});
			} else {
				jQuery('.form-message', $form).html(response).fadeIn();
			}
		},
		error: function() {
			alert('error in request');
		},
		exception: function() {
			alert('error in request');
		}
	});
	return false;
});
</script>