
<?php echo $this->partial('communication/contact/modal.phtml'); ?>
<?php if (!Elm::getSingleton('user/session')->isLoggedIn()) : ?>
    <div class="modal hide fade authenticate" id="sign-in">
        <a class="close" data-dismiss="modal">X</a>
        <h3 class="turquiose">Sign In</h3>
        <div class="modal-body">
            <p class="note">It's as easy as watching grass grow!</p>
            <?php echo $this->partial('partials/form/login.phtml'); ?>
        </div>
    </div>
    <div class="modal hide fade authenticate" id="sign-up">
        <a class="close" data-dismiss="modal">X</a>
        <h3 class="turquiose">Sign Up!</h3>
        <div class="modal-body">
            <p class="note">It's as easy as watching grass grow!</p>
            <?php echo $this->partial('partials/form/create.phtml'); ?>
        </div>
    </div>
<?php endif; ?>


<div id="action-loader" class="loader" style="display: none;"></div>
<script src="/file-bin/js/lib/bootstrap-combine.js" type="text/javascript"></script>
<script>
/*window.fbAsyncInit = function() {
	FB.init({
		appId      : 'YOUR_APP_ID', // App ID
		//channelUrl : '//<?php echo $this->Data()->getDomain() . $this->baseUrl('channel.html'); ?>', // Channel File
		status     : true, // check login status
		cookie     : true, // enable cookies to allow the server to access the session
		xfbml      : true  // parse XFBML
	});
};*/


// Load Asynchronously
// fb
!function(d, s, id) {
	// FB
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) {
		return;
	}
	js = d.createElement(s);
	js.id = id;
	js.src = "https://connect.facebook.net/en_US/all.js#xfbml=1";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk');
// g+
!function(d, s) {
	var po = d.createElement(s);
	po.type = 'text/javascript';
	po.async = true;
	po.src = 'https://apis.google.com/js/plusone.js';
	var s = d.getElementsByTagName(s)[0];
	s.parentNode.insertBefore(po, s);
}(document, 'script');
// twitter
!function(d, s, id) {
	var js,fjs = d.getElementsByTagName(s)[0];
	if(!d.getElementById(id)) {
		js = d.createElement(s);
		js.id = id;
		js.src = "https://platform.twitter.com/widgets.js";
		fjs.parentNode.insertBefore(js, fjs);
	}
}(document, 'script', 'twitter-wjs');
</script>
<script id="_webengage_script_tag" type="text/javascript">
window.webengageWidgetInit = window.webengageWidgetInit || function(){
	webengage.init({
		licenseCode:"~47b66612"
	}).onReady(function(){
		webengage.render();
	});
};
(function(d){
	var _we = d.createElement('script');
	_we.type = 'text/javascript';
	_we.async = true;
	_we.src = (d.location.protocol == 'https:' ? "//ssl.widgets.webengage.com" : "//cdn.widgets.webengage.com") + "/js/widget/webengage-min-v-3.0.js";
	var _sNode = d.getElementById('_webengage_script_tag');
	_sNode.parentNode.insertBefore(_we, _sNode);
})(document);
</script>