<footer id="footer">
    <div class="container clearfix">
        <div class="column">
            <h3>Resources</h3>
            <ul class="list">
                <li><a href="<?= $this->url('about-us'); ?>">About Us</a></li>
                <li><a href="<?= $this->url('marketplace'); ?>">Marketplace</a></li>
                <li><a href="<?php echo $this->url('how-it-works'); ?>">How it Works</a></li>
                <li><a href="<?php echo $this->url('about-us'); ?>">Help</a></li>
            </ul>
        </div>
        <div class="column">
            <h3>Help Us Grow</h3>
            <ul class="list-block social">
                <li><a class="icon twitter" href="http://twitter.com/@EveryLastMorsel" target="_blank" rel="twitter" title="Tweet With Us"></a></li>
                <li><a class="icon facebook" href="https://www.facebook.com/everylastmorsel" target="_blank" rel="facebook" title="Facebook Us"></a></li>
            </ul>
        </div>
        <div class="column newsletter">
            <h3>Sign Up For News & Updates</h3>
            <form class="email-signup" action="<?= $this->url('newsletter/signup'); ?>" method="post">
                <input type="email" name="email" id="email" />
                <button type="submit" name="submit" class="btn btn-blue"><span>Submit</span></button>
            </form>
        </div>
        <div class="copyright f-left">
            <p>Copyright &copy; Every Last Morsel 2013</p>
            <ul class="list-inline">
                <li><a href="Terms of Service">Terms of Service</a><span class="separator">|</span></li>
                <li><a href="Privacy Policy">Privacy Policy</a></li>
            </ul>
        </div>
        <div class="watermark"></div>
    </div>
</footer>

<?php if ($this->canContact) : ?>
	<?php echo $this->partial('communication/_modal.phtml'); ?>
<?php endif; ?>

<div id="action-loader" class="loader" style="display: none;"></div>
<div class="modal hide fade" id="globalMessageModal">
	<!--<div class="modal-header"><a class="close" data-dismiss="modal">×</a></div>-->
	<div class="modal-body">
		<h3></h3>
		<div class="buttons-set">
			<a class="button-link close" data-dismiss="modal">Close</a>
		</div>
	</div>
</div>
<script src="/file-bin/js/lib/bootstrap-combine.js" type="text/javascript"></script>
<script>
/*window.fbAsyncInit = function() {
	FB.init({
		appId      : 'YOUR_APP_ID', // App ID
		//channelUrl : '//<?php echo $this->Data()->getDomain() . $this->baseUrl('channel.html'); ?>', // Channel File
		status     : true, // check login status
		cookie     : true, // enable cookies to allow the server to access the session
		xfbml      : true  // parse XFBML
	});
};*/


// Load Asynchronously
// fb
!function(d, s, id) {
	// FB
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) {
		return;
	}
	js = d.createElement(s);
	js.id = id;
	js.src = "https://connect.facebook.net/en_US/all.js#xfbml=1";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk');
// g+
!function(d, s) {
	var po = d.createElement(s);
	po.type = 'text/javascript';
	po.async = true;
	po.src = 'https://apis.google.com/js/plusone.js';
	var s = d.getElementsByTagName(s)[0];
	s.parentNode.insertBefore(po, s);
}(document, 'script');
// twitter
!function(d, s, id) {
	var js,fjs = d.getElementsByTagName(s)[0];
	if(!d.getElementById(id)) {
		js = d.createElement(s);
		js.id = id;
		js.src = "https://platform.twitter.com/widgets.js";
		fjs.parentNode.insertBefore(js, fjs);
	}
}(document, 'script', 'twitter-wjs');
</script>
<script id="_webengage_script_tag" type="text/javascript">
window.webengageWidgetInit = window.webengageWidgetInit || function(){
	webengage.init({
		licenseCode:"~47b66612"
	}).onReady(function(){
		webengage.render();
	});
};
(function(d){
	var _we = d.createElement('script');
	_we.type = 'text/javascript';
	_we.async = true;
	_we.src = (d.location.protocol == 'https:' ? "//ssl.widgets.webengage.com" : "//cdn.widgets.webengage.com") + "/js/widget/webengage-min-v-3.0.js";
	var _sNode = d.getElementById('_webengage_script_tag');
	_sNode.parentNode.insertBefore(_we, _sNode);
})(document);
</script>