<div class="footer-container">
	<footer id="footer" role="" class="container_12 clearfix">
		<ul class="list left">
			<li><a href="<?= $this->url('about-us'); ?>">About Us</a></li>
			<li><a href="<?= $this->url(''); ?>">Map A Garden</a></li>
			<li><a href="<?= $this->url('help-us-grow'); ?>">Help Us Grow</a></li>
		</ul>
		<div class="branding"></div>

		<div class="signups">
			<h4>Help us grow</h4>
			<ul class="list-block social">
				<li><a href="http://twitter.com/@EveryLastMorsel" target="_blank" rel="twitter" title="Tweet With Us"></a></li>
				<li><a href="https://www.facebook.com/everylastmorsel" target="_blank" rel="facebook" title="Facebook Us"></a></li>
			</ul>
			<form class="email-signup" action="<?= $this->url('newsletter/signup'); ?>" method="post">
				<label for="email">Email sign up:</label>
				<input type="email" name="email" id="email" />
				<button type="submit" name="submit" class="link-btn">submit</button>
			</form>
			<!--<form class="search" action="<?/*= $this->url('search'); */?>" method="post">
				<label for="search">Search:</label>
				<input type="text" name="search" id="search" />
				<button type="submit" name="submit" class="link-btn">search</button>
			</form>-->
		</div>
	</footer>
</div>
<?php if ($this->canContact) : ?>
	<?php echo $this->partial('communication/_modal.phtml'); ?>
<?php endif; ?>

<script src="/file-bin/js/lib/bootstrap/bootstrap-modal.js" type="text/javascript"></script>
<script>
/*window.fbAsyncInit = function() {
	FB.init({
		appId      : 'YOUR_APP_ID', // App ID
		//channelUrl : '//<?php echo $this->Data()->getDomain() . $this->baseUrl('channel.html'); ?>', // Channel File
		status     : true, // check login status
		cookie     : true, // enable cookies to allow the server to access the session
		xfbml      : true  // parse XFBML
	});
};*/


// Load Asynchronously
// fb
!function(d, s, id) {
	// FB
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) {
		return;
	}
	js = d.createElement(s);
	js.id = id;
	js.src = "https://connect.facebook.net/en_US/all.js#xfbml=1";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk');
// g+
!function(d, s) {
	var po = d.createElement(s);
	po.type = 'text/javascript';
	po.async = true;
	po.src = 'https://apis.google.com/js/plusone.js';
	var s = d.getElementsByTagName(s)[0];
	s.parentNode.insertBefore(po, s);
}(document, 'script');
// twitter
!function(d, s, id) {
	var js,fjs = d.getElementsByTagName(s)[0];
	if(!d.getElementById(id)) {
		js = d.createElement(s);
		js.id = id;
		js.src = "https://platform.twitter.com/widgets.js";
		fjs.parentNode.insertBefore(js, fjs);
	}
}(document, 'script', 'twitter-wjs');
</script>
<script id="_webengage_script_tag" type="text/javascript">
window.webengageWidgetInit = window.webengageWidgetInit || function(){
	webengage.init({
		licenseCode:"~47b66612"
	}).onReady(function(){
		webengage.render();
	});
};
(function(d){
	var _we = d.createElement('script');
	_we.type = 'text/javascript';
	_we.async = true;
	_we.src = (d.location.protocol == 'https:' ? "//ssl.widgets.webengage.com" : "//cdn.widgets.webengage.com") + "/js/widget/webengage-min-v-3.0.js";
	var _sNode = d.getElementById('_webengage_script_tag');
	_sNode.parentNode.insertBefore(_we, _sNode);
})(document);
</script>