<footer id="footer">
    <div class="container clearfix">
        <div class="column">
            <h3>Resources</h3>
            <ul class="list">
                <li><a href="<?= $this->url('about-us'); ?>">About Us</a></li>
                <li><a href="<?= $this->url('marketplace'); ?>">Marketplace</a></li>
                <li><a href="<?php echo $this->url('how-it-works'); ?>">How it Works</a></li>
                <li><a href="<?php echo $this->url('about-us'); ?>">Help</a></li>
            </ul>
        </div>
        <div class="column">
            <h3>Help Us Grow</h3>
            <ul class="list-block social">
                <li><a class="icon twitter" href="http://twitter.com/@EveryLastMorsel" target="_blank" rel="twitter" title="Tweet With Us"></a></li>
                <li><a class="icon facebook" href="https://www.facebook.com/everylastmorsel" target="_blank" rel="facebook" title="Facebook Us"></a></li>
            </ul>
        </div>
        <div class="column newsletter">
            <h3>Sign Up For News & Updates</h3>
            <form action="<?= $this->url('newsletter/signup'); ?>" method="post" class="labelify email-signup">
                <label for="newsletter-email">Email</label>
                <div>
                    <input type="email" name="email" id="newsletter-email" />
                </div>
                <button type="submit" name="submit" class="btn btn-blue"><span>Submit</span></button>
            </form>
        </div>
        <div class="copyright f-left">
            <p>Copyright &copy; Every Last Morsel 2013</p>
            <ul class="list-inline">
                <li><a href="Terms of Service">Terms of Service</a><span class="separator">|</span></li>
                <li><a href="Privacy Policy">Privacy Policy</a></li>
            </ul>
        </div>
        <div class="watermark"></div>
    </div>
</footer>