
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>

<!--<link href='http://fonts.googleapis.com/css?family=Tenor+Sans|Varela' rel='stylesheet' type='text/css' />-->
<link href='http://fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'/>
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<script>
var Elm = {
	domain : '//<?php echo $this->Data()->getDomain(); ?>',
	environment : '<?php echo $this->Data()->getEnvironment(); ?>',
	api : '<?/*php echo $this->Data()->getMapsApi(); */?>'
};
window.Elm = Elm;
</script>
<?php echo $this->headScript(); ?>

<link href="/favicon.ico" rel="shortcut icon" />
