
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<?= $this->headMeta(); ?>
<?= $this->headTitle(); ?>

<link href='http://fonts.googleapis.com/css?family=Tenor+Sans|Varela' rel='stylesheet' type='text/css' />
<?= $this->headStyle(); ?>
<?= $this->headLink(); ?>
<?= $this->headScript(); ?>

<link href="/favicon.ico" rel="shortcut icon" />

<script>
var Elm = {
	domain : '//<?php echo $this->Data()->getDomain(); ?>',
	environment : '<?php echo $this->Data()->getEnvironment(); ?>',
	api : '<?php echo $this->Data()->getMapsApi(); ?>'
};
window.Elm = Elm;
</script>