<?php
$_session = Elm::getSingleton('user/session');
?>
<div class="utility">
    <div class="container">
        <ul class="list-inline t-right">
        <?php if ($_session->isLoggedIn()) : ?>
            <li>Howdy, <?php echo $_session->getUser()->getFullname(); ?>!<span class="separator">|</span></li>
            <li><a href="<?php echo $this->url('profile/settings'); ?>" title="Account Settings">Account Settings</a><span class="separator">|</span></li>
            <li><a href="<?php echo $this->url('profile/logout'); ?>" title="Logout">Sign Out</a></li>
        <?php else : ?>
            <li><a href="<?php echo $this->url('profile/create'); ?>" title="Sign Up">Sign Up</a><span class="separator">|</span></li>
            <li><a href="<?php echo $this->url('profile/login'); ?>" title="Sign In">Sign In</a></li>
        <?php endif; ?>
        </ul>
    </div>
</div>
<header id="header" class="container clearfix">
    <h1>
        <a href="<?php echo $this->url('/'); ?>" title="Every Last Morsel" class="ext-hide">
            <img src="<?php echo Elm::getBaseUrl('file-bin/images/logo.gif'); ?>" alt="Every Last Morsel" title="Every Last Morsel" />
        </a>
    </h1>
    <nav role="navigation">
        <ul class="list-inline t-right">
            <li><a href="<?php echo $this->url('map'); ?>" title="Map">Map</a></li>
            <li><a href="<?php echo $this->url('marketplace'); ?>" title="Marketplace">Marketplace</a></li>
            <li><a href="<?php echo $this->url('about-us'); ?>" title="About Us">About Us</a></li>
            <li><a href="<?php echo $this->url('help'); ?>" title="Help">Help</a></li>
        </ul>
    </nav>
    <div id="search" class="no-display"></div>
</header>

<?php echo $this->partial('profile/_login-menu.phtml'); ?>
