<?= $this->doctype(); ?>
<!--[if IE 8]><html class="ie8" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if gt IE 9]><!--><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><!--<![endif]-->
<head>
	<?= $this->render('head.phtml'); ?>
</head>
<body class="<?= $this->bodyClass; ?>">
	<div id="fb-root"></div>
	<div class="wrapper">
		<div class="page clearfix">
			<div class="header-container">
				<?= $this->render('header.phtml'); ?>
			</div>
			<div class="main-container">
				<div id="content" role="contentinfo" class="clearfix">
					<?= $this->layout()->content; ?>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

