<?= $this->doctype(); ?>
<!--[if IE 8]><html class="ie8" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if gt IE 9]><!--><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><!--<![endif]-->
<head>
	<?= $this->render('head.phtml'); ?>
</head>
<body class="<?= $this->bodyClass; ?> two-column">
	<div id="fb-root"></div>
	<div class="wrapper">
		<div class="page clearfix">
			<div class="header-container">
				<?= $this->render('header.phtml'); ?>
			</div>
			<div class="main-container">
				<div class="two-column profile-layout clearfix container_12">
					<div id="column-left" role="aside" class="column-left">
						<?php if (strlen($this->placeholder('sidebar')) > 0) : ?>
							<?= $this->placeholder('sidebar'); ?>
						<?php endif; ?>
					</div>
					<div id="content" role="contentinfo" class="main-content clearfix">
						<?= $this->layout()->content; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
    <div class="footer-container">
        <?= $this->render('footer.phtml'); ?>
    </div>
</body>
</html>

