<?php $plot = $this->plot; ?>
<ul class="list-block">
	<li class="crops-grid">
	<?php if ($plot->getCrops()) : ?>
		<ul>
			<li class="heading">
				<h4>Name</h4>
				<span>Condition</span>
				<span class="date">Date Planted</span>
				<span>Qty</span>
				<span>Yield</span>
				<span class="date">Est Pick Date/Picked Date</span>
				<span class="actions">Actions</span>
			</li>
		<?php foreach ($plot->getCrops() as $crop) : ?>
			<li class="crop">
				<?php if ($crop->getIsForSale()) : ?>
				<span class="icons"></span>
				<?php endif; ?>
				<h4><?= $crop->getCrop()->getName(); ?></h4>
				<span><?= $crop->getCondition() ? $crop->getCondition() : '&nbsp;'; ?></span>
				<span class="date"><?= $crop->getDatePlanted(); ?></span>
				<span><?= $crop->getQuantity(); ?></span>
				<span><?= $crop->getYield() ? $crop->getYield() : '&nbsp;'; ?></span>
				<span class="date"><?= $crop->getPickDate() ? $crop->getPickDate() : '&nbsp;'; ?></span>
				<span class="actions">
					<a href="#">Add Yield (+)</a>
				<?php if (!$crop->getIsForSale()) : ?>
					<a href="#">Mark For Sale ($) </a>
				<?php endif; ?>
				</span>
			</li>
		<?php endforeach; ?>
		</ul>
	<?php else : ?>
		<p>You no crops. Get growing!</p>
	<?php endif; ?>
	</li>
</ul>