<?php
$_session = Elm::getSingleton('user/session');
$_helper = new Elm_View_Helper_Form();
?>
<?php if (!$_session->isLoggedIn()) : ?>
	<form action="<?php echo $_helper->getLoginForm()->getAction(); ?>" method="post" id="header-form-validate">
		<ul class="fieldset">
			<li>
				<label for="email">Email:</label>
				<div>
					<input type="email" name="email" />
				</div>
			</li>
			<li>
				<label for="email">Password:</label>
				<div>
					<input type="password" name="password" />
				</div>
			</li>
		</ul>
		<div class="buttons-set">
			<button type="submit" class="btn btn-green" id="login-submit"><span>Sign me in!</span></button>
			<a href="#cancel" class="cancel">cancel</a>
		</div>
	</form>
<?php endif; ?>