<?php
$session = Elm::getSingleton('user/session');
?>
<?php if (Zend_Registry::isRegistered('current_user')) : ?>
	<?php $_user = Zend_Registry::get('current_user'); ?>
	<figure id="mainImage">
		<img src="<?php echo $this->User()->getImage($_user); ?>" title="<?php echo $_user->getName(); ?>" width="200px" />
	</figure>
	<div id="lowerColumn">
		<?php if ($session->isLoggedIn() && !$session->user->isMe($_user) && strlen($this->placeholder('contact-modal')) > 0) : ?>
			<p class="buttons">
				<a href="#contactModal" class="btn btn-primary contact-button" data-toggle="modal" title="Contact <?php echo $_user->getName(); ?>"><span>Send Email</span></a>
			</p>

			<?= $this->placeholder('contact-modal'); ?>
		<?php endif; ?>

		<?php if ($session->isLoggedIn() && $session->user->isMe($_user)) : ?>
		<!--<ul id="userHub">
			<li>something here</li>
			<li>something here 2</li>
			<li>something here 3</li>
		</ul>-->
		<?php endif; ?>
	</div>
<?php endif; ?>