<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<div class="top">
		<h2><?php echo $user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $user->getCity(); ?>,</li>
			<li><?php echo $user->getState(); ?></li>
		</ul>
	</div>

	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('profile/_navigation.phtml', array('plots' => $user->getPlots())); ?>

	<h2 class="blue">About <?= $user->getFirstname(); ?></h2>
	<div id="about" class="blocked-content about-me">
		<p><?= str_replace('<br />', '</p><p>', nl2br($user->getAbout())); ?></p>
	</div>
</div>