<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('profile/_navigation.phtml', array('plots' => $user->getPlots())); ?>

	<h2 class="blue">About <?= $user->getFirstname(); ?></h2>
	<div id="about" class="blocked-content about-me">
		<p><?= str_replace('<br />', '</p><p>', nl2br($this->escape($user->getAbout()))); ?></p>
	</div>
</div>