<?php
$_session = Elm::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper profile">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_user->getLocation(); ?></li>
			<li><?php echo $_user->getLocation(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('profile/_navigation.phtml', array('plots' => $_user->getPlots())); ?>

	<h2 class="blue">About <?= $_user->getFirstname(); ?></h2>
	<div id="about" class="blocked-content about-me">
		<p><?= str_replace('<br />', '</p><p>', nl2br($_user->getAbout())); ?></p>
	</div>
</div>