
<div class="account-form account-create container_12">
	<h1 class="turquiose">Sign Up. <span class="light-green">It's as easy as watching grass grow!</span></h1>
    <?php echo $this->Message()->render(); ?>
    <form action="<?php echo $this->form->getAction() ?>" method="post" id="form-validate">
        <ul class="fieldset">
			<?php foreach($this->form->getElements() as $element) : ?>
				<?php echo $element->render(); ?>
			<?php endforeach; ?>
		</ul>
		<div class="buttons-set">
			<button type="submit" class="btn btn-blue" id="create-submit"><span>Now sign me up!</span></button>
		</div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        //var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
</div>
