<?php
$_session = Elm::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper profile">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_user->getLocation(); ?></li>
			<li><?php echo $_user->getLocation(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('profile/_navigation.phtml', array('plots' => $_user->getPlots())); ?>

	<div id="plots" class="blocked-content clearfix">
		<?php echo $this->partial('plot/list.phtml', array('plots' => $_user->getPlots())); ?>
	</div>
</div>