<?php
$_session = Elm::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper profile">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_user->getLocation(); ?></li>
			<li><?php echo $_user->getLocation(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('profile/_navigation.phtml'); ?>

	<div id="plotsList" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('plots/list.phtml', array('plots' => $_user->getPlots(), 'details' => true)); ?>
	</div>

	<div id="feed" class="blocked-content">
		<?php //echo $this->partial('profile/feed/list.phtml', array('user' => $_user)); ?>
	</div>
</div>