<?php
$_session = Elm::getSingleton('user/session');
$_user = $this->user;
?>
<?php echo $this->Message()->render(); ?>
<div class="inner-content-wrapper plots">
	<div class="top">
		<h2><?php echo $_user->getName(); ?></h2>
		<ul class="list-inline">
			<li><?php echo $_user->getLocation(); ?></li>
			<li><?php echo $_user->getLocation(); ?></li>
		</ul>
	</div>

	<?php echo $this->partial('profile/_navigation.phtml'); ?>

	<h2 class="blue">Plots</h2>
	<div id="plotsList" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('plots/list.phtml', array('plots' => $_session->getUser()->getPlots(), 'details' => true)); ?>
	</div>
</div>