<?php
$helper = new Elm_View_Helper_Form();
$helper->getLoginForm()->setAttrib('labelify', true);
//$this->url('profile/login-postAjax');
?>
<form action="<?php echo $helper->getLoginForm()->getAction(); ?>" class="labelify" method="post" id="login-form-validate">
    <ul class="fieldset">
        <li>
            <label for="email">Email</label>
            <div>
                <input type="email" name="email" />
            </div>
        </li>
        <li>
            <label for="email">Password</label>
            <div>
                <input type="password" name="password" />
            </div>
        </li>
    </ul>
    <div class="buttons-set">
        <button type="submit" class="btn btn-orange submit icon secure"><span><span>Sign in</span></span></button>
    </div>
</form>
<script type="text/javascript">
jQuery("#login-form-validate").validate({
    onkeyup: false,
    rules: {
        email: {
            required: true,
            email: true
        },
        password: {required : true}
    },
    messages: {
        email : "Incorrect email format",
        password : "Please provide a password"
    },
    submitHandler : function(form) {
        window.event.preventDefault();
        Elm.Auth.Login(jQuery(form));
        return false;
    }
});
</script>