<?php
$session = Elm::getSingleton('user/session');
$plot = $this->plot;
?>
<?php if ($session->isLoggedIn() && !$plot->isAssociated($session->user)) : ?>
	<p class="get-involved">
		<a href="#involve-me" class="btn btn-blue btn-large" data-toggle="modal"><span>Get Involed</span></a>
	</p>

	<div class="modal hide fade" id="involveMeModal">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">×</a>
			<h3>Get Involved</h3>
		</div>
		<div class="modal-body">
			<form action="<?= $this->url('plot/involve-me'); ?>" method="post" id="getInvolvedModalForm">
				<input type="hidden" name="user_id" value="<?php echo Elm::getSingleton('user/session')->user->getId(); ?>" />
				<input type="hidden" name="plot_id" value="<?php echo $this->plot->getId(); ?>" />
				<ul class="fieldset">
				<?php foreach (Elm_Model_Resource_Plot::$userRoles as $role) : ?>
					<?php if ($role == 'Creator' || $role == 'Watcher') continue; ?>
					<li class="radio">
						<label class="radio" for="role<?php echo $role; ?>">
							<input type="radio" id="role<?php echo $role; ?>" class="radio-input" name="role" value="<?php echo $role; ?>">
							<?php echo $role; ?>
						</label>
					</li>
				<?php endforeach; ?>
				</ul>
				<div class="buttons-set">
					<button type="submit" class="btn btn-green" id="contact-submit"><span>Involve Me</span></button>
					<a href="#cancel" class="cancel" data-dismiss="modal">cancel</a>
				</div>
			</form>
		</div>
	</div>
	<div class="modal hide fade" id="involveMeSuccessModal">
		<div class="modal-header"><a class="close" data-dismiss="modal">×</a></div>
		<div class="modal-body"><h3>Successfully sent note!</h3></div>
	</div>
<?php endif; ?>