<?php if ($users = $this->plot->getUsers()) : ?>
	<ul class="list-inline">
	<?php foreach ($users as $user) : ?>
		<li>
			<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $user->getName(); ?>" width="150px" />
			<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $user->getName(); ?>"><?php echo $user->getName(); ?></a></h3>
			<?php echo $user->getUserRole(); ?>
		</li>
	<?php endforeach; ?>
	</ul>
<?php else : ?>
	<p>Sorry no users associated. Get growing!</p>
<?php endif; ?>