<?php
$plot = $this->plot;
$session = Elm::getSingleton('user/session');
$hasYields = $this->Yields()->plotHasYields($plot);
$hasActions = $this->Plot()->hasCropsForSale($plot);
$columnCount = ($hasYields && $hasActions) ? 6 : (($hasYields || $hasActions) ? 5 : 4);
?>
<?php if ($plot->getCrops()) : ?>
	<table class="data-table crops" width="100%">
		<colgroup>
			<col class="plant-type" />
			<col class="variety" />
			<col class="date" />
			<col class="coverage" />
		<?php if ($hasYields) : ?>
			<col class="total-yield" />
		<?php endif; ?>
		<?php if ($hasActions) : ?>
			<col class="actions" />
		<?php endif; ?>
		</colgroup>
		<thead>
			<tr>
				<th>Plant Type</th>
				<th>Variety</th>
				<th>Date Planted</th>
				<th>Coverage</th>
			<?php if ($hasYields) : ?>
				<th>Yield</th>
			<?php endif; ?>
			<?php if ($hasActions) : ?>
				<th></th>
			<?php endif; ?>
			</tr>
		</thead>
		<tbody>
		<?php $ctr = 0; ?>
		<?php foreach ($plot->getCrops() as $pCrop) : ?>
			<tr class="<?php echo ($ctr++ % 2) ? '' : 'alt'; ?>">
				<td><?= ucwords($pCrop->getCrop()->getType()); ?></td>
				<td><?= $this->escape($pCrop->getCrop()->getVariety()); ?></td>
				<td><?= $this->Data()->formatDate($pCrop->getDatePlanted()); ?></td>
				<td><?= $pCrop->getCoverage(); ?> <?= $pCrop->getCoverageUnits(); ?></td>
			<?php if ($hasYields) : ?>
				<td id="crop-yields-totals-<?php echo $pCrop->getId(); ?>"><?php echo $this->partial('crops/yields/_totals.phtml', array('pCrop' => $pCrop)); ?></td>
			<?php endif; ?>
			<?php if ($hasActions) : ?>
				<td id="crop-yield-actions-<?php echo $pCrop->getId(); ?>">
					<?php if ($pCrop->getIsForSale()) : ?>
						<a href="#is-for-sale" title="For Sale">For Sale</a>
					<?php endif; ?>
				</td>
			<?php endif; ?>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>