<?php
$plot = $this->plot;
?>
<?php if ($plot->getCrops()) : ?>
	<table class="data-table" width="100%">
		<colgroup>
			<col class="plant-type" />
			<col class="variety" />
			<col class="date" />
			<col class="coverage" />
			<col class="actions" />
		</colgroup>
		<thead>
			<tr>
				<th>Plant Type</th>
				<th>Variety</th>
				<th>Date Planted</th>
				<th>Coverage</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		<?php $ctr = 0; ?>
		<?php foreach ($plot->getCrops() as $pCrop) : ?>
			<tr class="<?php echo ($ctr++ % 2) ? '' : 'alt'; ?>">
				<td><?= ucwords($pCrop->getCrop()->getType()); ?></td>
				<td><?= $this->escape($pCrop->getCrop()->getVariety()); ?></td>
				<td><?= $this->Data()->formatDate($pCrop->getDatePlanted()); ?></td>
				<td><?= $pCrop->getCoverage(); ?> <?= $pCrop->getCoverageUnits(); ?></td>
				<td>
					<a href="#addYieldModal" data-toggle="modal">Add Yield</a>
					<?php if ($pCrop->getIsForSale()) : ?>
						<span class="separator">|</span>
						<a href="#is-for-sale">For Sale</a>
					<?php endif; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
	<div class="modal hide fade" id="addYieldModal">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">×</a>
			<h3>Add Yield</h3>
		</div>
		<div class="modal-body">
			<?php echo $this->partial('yields/_form.phtml'); ?>
		</div>
	</div>

<?php else : ?>
	<p>Nothing has been planted yet. Get growin'!</p>
<?php endif; ?>