<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
$plot = $this->plot;
$form = $this->form;
?>
<div class="inner-content-wrapper crops">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

	<h2 class="blue"><?= $this->escape($plot->getName()); ?></h2>
	<div id="crops" class="blocked-content clearfix crops"">
		<?php echo $this->partial('crops/manage/_list.phtml', array('plot' => $plot)); ?>
	</div>

	<div id="cropsForm" class="blocked-content clearfix">
		<?php echo $this->partial('crops/_form.phtml', array('view' => $this)); ?>
	</div>
</div>