<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
$plots = $user->getNonWatching();
?>
<div class="inner-content-wrapper crops">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

	<?php if (count($plots)) : ?>
		<ul class="list-block list details">
		<?php foreach ($plots as $plot) : ?>
			<li>
				<figure>
					<img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '150', 'width' => '150'))); ?>" title="<?php echo $this->escape($plot->getName()); ?>" />
				</figure>
				<div class="plot-details details">
					<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $this->escape($plot->getName()); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
					<p class="role"><b><?php echo $plot->getUserRole(); ?></b></p>
					<p><?php echo $this->escape($plot->getAbout()); ?></p>
					<p class="buttons-set">
						<a href="<?php echo $this->url('crops/manage', array('p' => $plot->getId())); ?>" class="btn btn-grey" title="Manage Crops"><span>Manage Crops</span></a>
					</p>
				</div>
				<div class="crops-container">
					<div id="crops" class="blocked-content clearfix">
						<?php echo $this->partial('crops/_list.phtml', array('plot' => $plot)); ?>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	<?php endif; ?>
</div>