<?php
$_session = Elm::getSingleton('user/session');
$total = count($this->users);
$ctr = 0;
$columnCount = 4;
?>
<div class="clearfix container_12 community">
	<?php echo $this->partial('community/_navigation.phtml'); ?>
	<div class="blocked-content people">
		<?php foreach ($this->users as $user) : ?>
			<?php if ($ctr % $columnCount == 0) : ?>
			<ul class="list-block user-list list">
			<?php endif; ?>
			<li>
				<figure><img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $this->escape($user->getName()); ?>" width="205px" /></figure>
				<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $this->escape($user->getName()); ?>"><?php echo $this->escape($user->getName()); ?></a></h3>
				<p class="role"><?php echo $user->getGardenerType(); ?></p>
			</li>
			<?php if (++$ctr % $columnCount == 0 || $ctr == $total) : ?>
			<ul class="list-block user-list list">
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
</div>