<?php
$_session = Elm::getSingleton('user/session');
$total = count($this->users);
$ctr = 0;
$columnCount = 4;
?>
<div class="clearfix container_12 community">
	<?php echo $this->partial('community/_navigation.phtml'); ?>
	<div class="blocked-content plots">
		<?php foreach ($this->plots as $plot) : ?>
			<?php if ($ctr % $columnCount == 0) : ?>
			<ul class="list-block user-list list">
			<?php endif; ?>
			<li>
				<figure>
					<img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '205', 'width' => '205'))); ?>" title="<?php echo $this->escape($plot->getName()); ?>" />
				</figure>
				<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $this->escape($plot->getName()); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
				<p class="role"><?php echo $plot->getUserRole(); ?></p>
			</li>
			<?php if (++$ctr % $columnCount == 0 || $ctr == $total) : ?>
			<ul class="list-block user-list list">
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
</div>