<?php $item = $this->item; ?>
<?php $_session = Bootstrap::getSingleton('user/session'); ?>
<li class="<?php echo $item->getType(); ?>">
	<div class="fLeft user-info">
		<img src="<?php echo $this->User()->getImage($item->getUser()); ?>" title="<?php echo $item->getUser()->getName(); ?>" width="75px" />
		<h3><?= $item->getUser()->getName(); ?></h3>
	</div>
	<div class="fLeft">
		<p><?= $item->getContent(); ?></p>
		<p><?= $item->getCreatedAt(); ?></p>
	</div>

	<?php if ($_session->isLoggedIn()) : ?>
		<div class="rate" id="rate-<?= $item->getId(); ?>">Rate it!</div>
		<div class="lower">
			<a href="#" class="leave-comment" title="Leave a Comment">Leave a Comment</a>
			<div class="comment-container hide" id="comment-form-<?= $item->getId(); ?>">
				<form action="<?php echo $this->url('comment/create'); ?>" method="post" class="comment-form">
					<input type="hidden" name="plot_id" value="<?= $item->getPlotId(); ?>" />
					<input type="hidden" name="user_id" value="<?= $_session->user->getId(); ?>" />
					<input type="hidden" name="parent_id" value="<?= $item->getId(); ?>" />
					<input type="hidden" name="type" value="text" />
					<p class="input">
						<label for="status-content">Leave a comment</label>
						<textarea id="status-content" name="content"></textarea>
					</p>
					<p class="buttons-set">
						<button class="btn btn-inverse" type="submit"><span>Share</span></button>
					</p>
				</form>
			</div>
		</div>
	<?php endif; ?>
</li>