<?php if ($feed = $this->Plot()->getFeed($this->plot, 10)) : ?>
<div class="comment-list">
	<h4>Comments</h4>
	<ul class="feed list-block" id="comment-feed-<?= $this->plot->getId(); ?>">
		<?php foreach ($feed as $item) : ?>
			<?php echo $this->partial('plot/comment/item.phtml', array('item' => $item)); ?>
		<?php endforeach; ?>
	</ul>
</div>

<script defer="defer">
!function($) {
	$('ul.feed').on('click', '.leave-comment', function(e) {
		e.preventDefault();
		var $container = $(this).parents('li').find('.comment-container');
		$container.slideToggle().toggleClass('active');
	});

	$('ul.feed').on('submit', '.comment-form', function(e) {
		e.preventDefault();
		var $form = $(this);
		var $alert = $form.find('.alert');

		if ($alert.length) {
			$alert.alert('close');
		}

		$.ajax({
			url: $form.attr('action'),
			type: 'post',
			data: $form.serialize(),
			success: function(response) {
				if (!elm.success(response)) {
					return;
				}

				if (response.success) {
					$.formReset($form);
					var $li = $(response.html).hide();
					$('.feed', '#socializing').prepend($li);
					$li.fadeIn();
					$form.parents('li').find('.leave-comment').trigger('click');
				} else {
					$alert = $.createErrorAlert(response.message).hide();
				}

				if ($alert.length) {
					$form.prepend($alert);
					$alert.fadeIn();
				}
			},
			error: function() {
				elm.error("Oops! We've encountered some troubles. Try again shortly!", $form, 'prepend');
			},
			exception: function() {
				elm.error("Oops! We've encountered some troubles. Try again shortly!", $form, 'prepend');
			}
		});
		return false;
	});
}(window.jQuery);
</script>
<?php endif; ?>