<?php
$session = Elm::getSingleton('user/session');
?>
<nav id="profileNavigation" class="styled">
    <ul class="list-block">
        <li><a href="<?php echo $this->url('profile'); ?>" title="About Me">About</a></li>
        <!--<li><a href="<?php /*echo $this->url('profile/news'); */?>" title="About Me">News</a></li>-->
        <li><a href="<?php echo $this->url('profile/plots'); ?>" title="My Plots">Plots</a></li>
        <li><a href="<?php echo $this->url('profile/crops'); ?>" title="My Crops">Crops</a></li>
    </ul>
</nav>