<?php
$session = Elm::getSingleton('user/session');
?>
<?php if (Zend_Registry::isRegistered('current_user')) : ?>
	<?php $user = Zend_Registry::get('current_user'); ?>
	<figure id="main-image">
		<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $this->escape($user->getName()); ?>" width="200px" />
	</figure>
    <?php if ($session->isLoggedIn()) : ?>
        <ul id="profile-navigation" class="utility-navigation">
            <li<?php if ($this->Data()->isActiveUrl($this->url('profile'))) : ?> class="active"<?php endif; ?>>
                <a href="<?php echo $this->url('profile'); ?>" title="My Profile"><span class="icon person"></span>My Profile</a>
            </li>
            <li<?php if ($this->Data()->isActiveUrl($this->url('communication/list'))) : ?> class="active"<?php endif; ?>>
                <a href="<?php echo $this->url('communication/list'); ?>" title="Communication Hub"><span class="icon drawer"></span>Communication Hub</a>
            </li>
            <li<?php if ($this->Data()->isActiveUrl($this->url('profile/settings'))) : ?> class="active"<?php endif; ?>>
                <a href="<?php echo $this->url('profile/settings'); ?>" title="Settings"><span class="icon cog"></span>Settings</a>
            </li>
        </ul>
    <?php endif; ?>
	<div id="lower-column">
        <?php if ($session->isLoggedIn() && !$session->isMe($user) && !$user->isPrivate()) : ?>
		<div class="buttons-set">
			<?php if ($this->canContact) : ?>
				<button type="button" class="btn btn-orange contact-owner contact-button" data-to="<?php echo $user->getId(); ?>">
                    <span>Contact <?php echo $this->escape($user->getFirstname()); ?>!</span>
                </button>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
<?php endif; ?>