<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->partial('partials/user/top-display.phtml', array('user' => $user)); ?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

    <?php if ($session->isMe($user)) : ?>
        <a href="#edit-about" class="button"><span>Edit About</span></a>
    <?php endif; ?>

    <?php if (strlen($user->getAbout()) > 0) : ?>
        <h2>About <?= $user->getFirstname(); ?></h2>
        <div id="about" class="blocked-content about-me">
            <?php echo $this->partial('partials/user/about.phtml', array('user' => $user)); ?>
        </div>
    <?php else : ?>
        <h3>Share a little about yourself. Everyone's eager to hear more!</h3>
    <?php endif; ?>
</div>