<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->partial('partials/user/top-display.phtml', array('user' => $user)); ?>
<div class="inner-content-wrapper profile about">
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

    <section class="content">
        <?php if ($session->isMe($user)) : ?>
            <p class="buttons-set">
                <a href="<?php echo $this->url('profile/about-edit'); ?>" class="btn wider btn-orange"><span>Edit About</span></a>
            </p>
        <?php endif; ?>

        <article>
            <?php if (strlen($user->getAbout()) > 0) : ?>
                <h2>About <?= $user->getFirstname(); ?></h2>
                <div id="about" class="blocked-content about-me">
                    <?php echo $this->partial('partials/about.phtml', array('about' => $user->getAbout())); ?>
                </div>
            <?php else : ?>
                <h3>Share a little about yourself. Everyone's eager to hear more!</h3>
            <?php endif; ?>
        </article>
    </section>
</div>