<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->partial('partials/user/top-display.phtml', array('user' => $user)); ?>
<div class="inner-content-wrapper profile about-edit">
	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
    <section class="content">
        <form action="<?php echo $this->form->getAction() ?>" method="post" class="labelify" id="about-edit-form">
            <ul class="fieldset">
                <?php foreach($this->form->getElements() as $element) : ?>
                    <?php echo $element->render(); ?>
                <?php endforeach; ?>
            </ul>
            <div class="buttons-set">
                <button type="submit" class="btn btn-orange submit"><span>Save Information</span></button>
            </div>
        </form>
    </section>
</div>