<?php
$session = Elm::getSingleton('user/session');
?>
<div class="account-form forgot-password container_12">
	<h1 class="turquiose">Hey! <span class="light-green">Allow us to help you remember!</span></h1>
    <?php echo $this->Message()->render(); ?>
    <form action="" method="post" id="form-validate">
        <ul class="fieldset">
			<li>
				<label for="email">Email</label>
				<div>
					<input type="email" name="email" id="email" value="<?= $session->forgotPasswordEmail; ?>" />
				</div>
			</li>
		</ul>
		<div class="buttons-set">
			<button type="submit" class="btn btn-blue" id="forgot-password-submit"><span>Reset</span></button>
		</div>
    </form>
</div>
