<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->partial('partials/user/top-display.phtml', array('user' => $user)); ?>
<div class="inner-content-wrapper plots">
	<?php echo $this->partial('profile/_navigation.phtml'); ?>
	<?php echo $this->Message()->render(); ?>

	<h2>My Plots</h2>
	<div id="plots-list" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('partials/plot/list.phtml', array('plots' => $user->getNonWatching(), 'details' => true)); ?>
	</div>
</div>