<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('profile/_navigation.phtml'); ?>

	<div id="plotsList" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('plots/_list.phtml', array('plots' => $user->getPlots(), 'details' => true)); ?>
	</div>

	<div id="feed" class="blocked-content">
		<?php //echo $this->partial('profile/feed/list.phtml', array('user' => $user)); ?>
	</div>
</div>