<?php
$session = Elm::getSingleton('user/session');
$users = $this->users;
?>
<?php if (count($users)) : ?>
	<?php if ($this->details) : ?>
		<ul class="list-block user-list">
		<?php foreach ($users as $user) : ?>
			<li>
				<figure>
					<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $this->escape($user->getName()); ?>" width="150px" />
				</figure>
				<div class="user-details details">
					<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $this->escape($user->getName()); ?>"><?php echo $this->escape($user->getName()); ?></a></h3>
					<p class="role">
						<?php if ($session->isMe($user)) : ?>
							<i>(Me)</i>
						<?php endif; ?>
					</p>
					<p><?php echo $this->escape($user->getAbout()); ?></p>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>

	<?php else : ?>
		<ul class="list-block user-list list">
		<?php foreach ($users as $user) : ?>
			<li>
				<figure>
					<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $this->escape($user->getName()); ?>" width="120px" />
				</figure>
				<h3><a href="<?php echo $user->getUrl(); ?>" title="<?php echo $this->escape($user->getName()); ?>"><?php echo $this->escape($user->getName()); ?></a></h3>
				<p class="role">
                    <?php if ($session->isMe($user)) : ?>
						<i>(Me)</i>
					<?php endif; ?>
				</p>
			</li>
		<?php endforeach; ?>
		</ul>
	<?php endif; ?>
<?php endif; ?>