<?php
$session = Elm::getSingleton('user/session');
?>
<?php if (Zend_Registry::isRegistered('current_user')) : ?>
	<?php $user = Zend_Registry::get('current_user'); ?>
	<figure id="main-image">
		<img src="<?php echo $this->User()->getImage($user); ?>" title="<?php echo $this->escape($user->getName()); ?>" width="200px" />
	</figure>
	<div id="lower-column">
		<?php if ($session->isLoggedIn() && !$session->isMe($user) && !$user->isPrivate()) : ?>
		<div class="buttons-set">
			<?php if ($this->canContact) : ?>
				<button type="button" class="btn btn-orange contact-owner contact-button" data-to="<?php echo $user->getId(); ?>"><span>Contact <?php echo $this->escape($user->getFirstname()); ?>!</span></button>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
<?php endif; ?>