<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<?php echo $this->partial('partials/user/top-display.phtml', array('user' => $user)); ?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_navigation.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>

    <?php if ($user->isPrivate()) : ?>
        <h2 class="private-user">This user has requested a little privacy.</h2>
    <?php else : ?>
        <?php if (strlen($user->getAbout()) > 0) : ?>
            <h3>About <?= $user->getFirstname(); ?></h3>
            <div id="about" class="blocked-content about-me">
                <?php echo $this->partial('partials/user/about.phtml', array('user' => $user)); ?>
            </div>
        <?php else : ?>
            <h3>Give them time, they have yet to settle in and share a little about them self.</h3>
        <?php endif; ?>
    <?php endif; ?>
</div>

