<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->partial('user/_navigation.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>

	<div id="plotsList" class="blocked-content clearfix plots-list">
		<ul class="list-block list details">
		<?php foreach ($user->getPlots() as $plot) : ?>
			<li>
				<figure>
					<img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '150', 'width' => '150'))); ?>" title="<?php echo $this->escape($plot->getName()); ?>" />
				</figure>
				<div class="plot-details details">
					<h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $this->escape($plot->getName()); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
					<p class="role"><b><?php echo $plot->getUserRole(); ?></b></p>
					<p><?php echo $this->escape($plot->getAbout()); ?></p>
				</div>
				<div class="crops-container">
					<div id="crops" class="blocked-content clearfix">
						<?php echo $this->partial('crops/_list.phtml', array('plot' => $plot)); ?>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
</div>