<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>
	<?php echo $this->partial('user/_navigation.phtml', array('user' => $user)); ?>

<?php if ($user->isPrivate()) : ?>
	<h2 class="private-user">This user is private.</h2>
<?php else : ?>
	<div id="plotsList" class="blocked-content clearfix plots-list">
		<?php echo $this->partial('plots/_list.phtml', array('plots' => $user->getPlots(), 'details' => true)); ?>
	</div>
<?php endif; ?>
</div>