<?php
$session = Elm::getSingleton('user/session');
$user = $this->user;
?>
<div class="inner-content-wrapper profile">
	<?php echo $this->partial('user/_top-display.phtml', array('user' => $user)); ?>
	<?php echo $this->partial('user/_navigation.phtml', array('user' => $user)); ?>
	<?php echo $this->Message()->render(); ?>

<?php if ($user->isPrivate()) : ?>
	<h2 class="private-user">This user is private.</h2>
<?php else : ?>
	<h2 class="blue">About <?= $this->escape($user->getFirstname()); ?></h2>
	<div id="about" class="blocked-content about-me">
		<p><?= str_replace('<br />', '</p><p>', nl2br($this->escape($user->getAbout()))); ?></p>
	</div>

	<div id="feed" class="blocked-content">
		<?php //echo $this->partial('profile/feed/list.phtml', array('user' => $user)); ?>
	</div>
<?php endif; ?>
</div>