
<?php if (count($this->plots) > 0) : ?>
    <?php if ($this->details) : ?>
        <ul class="list-block list details">
            <?php foreach ($this->plots as $plot) : ?>
                <li>
                    <figure>
                        <img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '150', 'width' => '150'))); ?>" title="<?php echo $this->escape($plot->getName()); ?>" />
                    </figure>
                    <div class="plot-details details">
                        <h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $this->escape($plot->getName()); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
                        <p class="role"><?php echo $plot->getUserRole(); ?></p>
                        <div class="description">
                            <?php echo $this->partial('partials/about.phtml', array('about' => $plot->getAbout())); ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <ul class="list-block grid">
            <?php foreach ($this->plots as $plot) : ?>
                <li>
                    <figure>
                        <img src="<?php echo $this->Map()->getMapImage($plot, array('size' => array('height' => '125', 'width' => '125'))); ?>" title="<?php echo $this->escape($plot->getName()); ?>" />
                    </figure>
                    <h3><a href="<?php echo $plot->getUrl(); ?>" title="<?php echo $this->escape($plot->getName()); ?>"><?php echo $this->escape($plot->getName()); ?></a></h3>
                    <p class="role"><?php echo $plot->getUserRole(); ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php else : ?>
    <h3>Gasp! It looks as if nothing has been planted.</h3>
<?php endif; ?>